### DISCUSSION TITLE
Is there a way I can set nodeselectors , tolerations and resource limits for all the pods that gets created as part of Job in the experiment workflow

### DISCUSSION THREAD

**Discussion by biplabMazumdar** [litmuschaos/litmus#4531] [Q&A]
Is there a way I can set nodeselectors , tolerations and resource limits for all the pods that gets created as part of Job in the experiment workflow

**Comment by thiha-min-thant** [comment]
Yes, you can set nodeSelectors, tolerations, and resource limits for all the pods created as part of a Job in an experiment workflow by configuring these parameters in the ChaosEngine resource under the components field of each experiment. Here’s how each one works and examples of how to implement them:

```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "default"
    applabel: "app=nginx"
    appkind: "deployment"
  chaosServiceAccount: pod-delete-sa
  experiments:
  - name: pod-delete
    spec:
      components:
        # nodeselector for the experiment pod
        nodeSelector:
          context: chaos
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
          cpu: "500m"
          memory: "128Mi"
        tolerations:
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "Schedule"
```

For more information on configuring these fields in your Chaos experiments, refer to the [LitmusChaos Documentation](https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/chaos-engine/experiment-components/#experiment-resource-requirements).
