### DISCUSSION TITLE
Litmus Experiment not working on OpenShift

### DISCUSSION THREAD

**Discussion by alininja** [litmuschaos/litmus#4540] [Q&A]
Hi Folks 👋 

Sorry, I am trying to get Litmus to work on an OpenShift cluster.

While inspecting the experiment YAML, I noticed these `kubectl` commands:
```
          ...
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
          ...
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
          ...
```

I tried changing `kubectl` to `oc` to troubleshoot/fix my first experiment not working, but the experiment failed even worse.  Reverting it back to `kubectl` worked better.

I am curious if there are other translations I need to do to get my first experiment working on OpenShift.

Is Litmus expected to work on OpenShift?

Thank you for your time and help 🙏 

PS: Full Experiment YAML
```
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: zhaoli--exemplar-application
  namespace: chaos-engineering--litmus--namespace-infrastructure
  creationTimestamp: null
  labels:
    infra_id: cd25e682-ab96-461d-b10e-e4c5c9930e95
    revision_id: 196fce2b-05c5-4bdc-a2a2-f69e5a6fe90e
    workflow_id: 71d2ba7c-886e-4bf2-a6be-ba65cb43a79d
    workflows.argoproj.io/controller-instanceid: cd25e682-ab96-461d-b10e-e4c5c9930e95
spec:
  templates:
    - name: zhaoli--exemplar-application
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: disk-fill-3nb
            template: disk-fill-3nb
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: disk-fill-3nb
            path: /tmp/disk-fill-3nb.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Fillup Ephemeral Storage of a Resource
                kind: ChaosExperiment
                metadata:
                  name: disk-fill
                  labels:
                    name: disk-fill
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 3.0.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:3.0.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name disk-fill
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: FILL_PERCENTAGE
                        value: "80"
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: DATA_BLOCK_SIZE
                        value: "256"
                      - name: TARGET_PODS
                        value: ""
                      - name: EPHEMERAL_STORAGE_MEBIBYTES
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: DEFAULT_HEALTH_CHECK
                        value: "false"
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:3.0.0
                      - name: CONTAINER_PATH
                        value: /var/lib/docker/containers
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: disk-fill
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/host-path-usage: "true"
                      app.kubernetes.io/version: 3.0.0
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
&& sleep 30
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: disk-fill-3nb
      inputs:
        artifacts:
          - name: disk-fill-3nb
            path: /tmp/chaosengine-disk-fill-3nb.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1
 
                kind: ChaosEngine
 
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: zhaoli--exemplar-application
                  annotations:
                    probeRef: '[{"name":"zhaoli--exemplar-application--http","mode":"OnChaos"}]'
                  generateName: disk-fill-3nb
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  appinfo:
                    appns: chaos-engineering--litmus--namespace-infrastructure
                    applabel: app=frontend
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: disk-fill
                      spec:
                        components:
                          env:
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: FILL_PERCENTAGE
                              value: "80"
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: RAMP_TIME
                              value: ""
                            - name: DATA_BLOCK_SIZE
                              value: "256"
                            - name: TARGET_PODS
                              value: ""
                            - name: EPHEMERAL_STORAGE_MEBIBYTES
                              value: ""
                            - name: NODE_LABEL
                              value: ""
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
                            - name: LIB_IMAGE
                              value: litmuschaos/go-runner:3.0.0
                            - name: CONTAINER_PATH
                              value: /var/lib/docker/containers
                            - name: SEQUENCE
                              value: parallel
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-disk-fill-3nb.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: zhaoli--exemplar-application
  arguments:
    parameters:
      - name: adminModeNamespace
        value: chaos-engineering--litmus--namespace-infrastructure
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
status:
  startedAt: null
  finishedAt: null
```
