### ISSUE TITLE
[feat]: add chaostype [app/infra] in engine spec

### ISSUE THREAD

**Issue by shubhamchaudhary** [litmuschaos/litmus#1012]
**What needs to be done**

-  Add chaosType in engine spec - it can be app/infra

```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine
  namespace: litmus
spec:
  chaosType: "infra"  < ----  Add chaos type here
  components:
    runner:
      image: "litmuschaos/ansible-runner:ci"
  appinfo:
    appns: litmus
    applabel: "run=nginx"
    appkind: deployment
  chaosServiceAccount: litmus
  monitoring: false
  experiments:
    - name: disk-loss
      spec:
        components:
```
**Why we need this**

- We need this because we don't want to check for annotation in infra chaos experiments i.e disk-loss.
   - If the chaos type is infra then we can skip annotation check 
   -  If the chaosType is app then we have to do an annotation check.
