### ISSUE TITLE
Differentiate the permission scope in infra chaos v/s app-level chaos experiment CRs 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1037]
Currently, the chaos experiment CRs consist of the schema item `spec.definition.permissions` to signify the resource permissions necessary to execute the chaos experiment, but do not specify whether they are needed at a namespace-scoped level or cluster-scoped level. 

For most app-level chaos experiments - such as pod-delete/container-kill/network-latency etc..,(that have a lower blast radius and typically impact only those apps  (and may be dependent ones) subjected to chaos it is preferable to specify the role(permissions) at a namespace-scope.

For the infra-level chaos experiments - such as node-drain, disk-loss etc.., (that have a higher blast radius and typically impact multiple apps and thereby need a multi-app status check, possibly  across namespaces) it is preferable to specify role(permissions) at a cluster-scope. 

While the chaos operator/runner is not using the data in spec.permissions to create/validate the chaosServiceAccount account capabilities today, it is still necessary to enable the right decisions by the developers/devops admins, while also allowing any higher-level tool/platform to read off this custom-resource.

**Comment by ksatchit** [comment]
Some suggestions wrt schema are here: 

```yaml
spec:
  definition:
    scope: 'namespace'
    permissions:
      apigroups: 
      - <>
      resources: 
      - <>
      verbs:
```

```yaml
spec:
  definition:
    roleType: 'namespace'
    permissions:
      apigroups: 
      - <>
      resources: 
      - <>
      verbs:
```
