### ISSUE TITLE
(feat): Schema changes (spec.components) to ensure the type of tunable is clear

### ISSUE THREAD

**Issue by shubhamchaudhary** [litmuschaos/litmus#1114]
**What needs to done**

- Schema changes (spec.components) to ensure the type of tunable is clear (env, configmap, secret)

- Update the chaosengine_crd.yaml with the latest changes 

**Why we need this**

- It Can allow chaos-engine to override ENV, configMaps and secrets. It will reduce the dependency on chaos-charts.

**Sampe Engine Manifest**
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine
spec:
  auxiliaryAppInfo: ""
  components:
    runner:
      image: "litmuschaos/chaos-executor:ci"
      type: "go"
  appinfo:
    appns: shubham
    applabel: "name=nginx1"
    appkind: deployment
  chaosServiceAccount: litmus
  monitoring: false
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'nginx'
          configmaps:
            - name: cmap
              mountPath: '/mnt/'
          secrets:
            - name: secret
              mountPath: '/tmp/'
```
