### ISSUE TITLE
Update experiment status and verdict in ChaosResult status

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1239]
Right now, the experiment status is being captured in the .spec of the resource, which is generally not the practice while updating custom resources. It needs to be moved to the .status field, while allowing the spec to hold static info/metadata on the experiment result such as (a) name of experiment (b) lineage/engine it is associated with etc.,

**Comment by ksatchit** [comment]
```yaml
---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosResult
metadata:
  {% if instance_id is defined %}
  name: {{ c_result }}-{{ instance_id }}
  {% else %}
  name: {{ c_result }}
  {% endif %} 
  labels:
    chaosUID: {{ uid }}
spec:
  experiment: {{ c_experiment }}
  instance: {{ instance_id }} 
status:
  experimentstatus: 
    phase: {{ phase }}  
    verdict: {{ verdict }}
   
```
