### ISSUE TITLE
Add support for generation of events for the experiment pod

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1244]
- Events to signify progress of the chaos injection business logic

**Comment by ksatchit** [comment]
- Here is a sample util to create events from the ansible experiment playbooks. We need to call this util (templatize all commented items in event spec) at stages : pre-check/chaos-inject/post-check. May help to establish standard format for: reason, message so that it can be consistent across experiments and also help director with appropriate filter/processing. Since we use the job/pod-name as the `event source` we may have to add the `metadata.name` downward api to set the pod name ENV. 

```yaml
 hosts: localhost
  connection: local
​
  tasks:
​
    ## this works perfectly, but we don't encourage 
    ## ansible_system_facts_gathering on slower setups
    ## via env DEFAULT_GATHERING: "explicit"
    
    #- name: Obtain current timestamp in ISO8601 format
    #  set_fact:
    #    ts: "{{ ansible_date_time.iso8601 }}"
​
    - name: Obtain the date in ISO8601 format
      shell: date --iso-8601=seconds
      register: date_from_linux_shell
​
    - set_fact:
        ts: "{{ date_from_linux_shell.stdout.split('+')[0] + 'Z'}}"
​
    - name: Create an test event on the chaosengine
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Event
          metadata:
		    # standardize for stages for experiment
            name: test-event-2
            namespace: default
          message: This is a test event generated into chaosengine
		  # change this as per stage of experiment
          reason: pre-check 
          source: 
		    # this needs to be replaced by the exp job/pod name
            component: experiment-pod
          type: Normal
          count: 1
          firstTimestamp: "{{ ts }}"
          involvedObject:
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
			# this needs to be replaced by actual chaosengine name
            name: nginx-chaos
			# this needs to be replaced by actual resource ns
            namespace: default
            ## uid is passed as env from chaos-runner
            uid: 4e0fea10-5ee9-11ea-ab06-42010a8000e9
```
