### ISSUE TITLE
node-drain experiment operator CrashLoopBackOff

### ISSUE THREAD

**Issue by jjmengze** [litmuschaos/litmus#1388]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

**What happened**:
When I tested the node-drain experiment, I found that if drain.yaml is configured as follows, chaos-operator-ce will crash.

```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be true/false
  annotationCheck: 'false'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
#  appinfo:
#    appns: 'default'
#    applabel: 'app=nginx'
#    appkind: 'deployment'
  chaosServiceAccount: node-drain-sa
  monitoring: false
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: node-drain
      spec:
        components:
          env:
            # set node name
            - name: APP_NODE
              value: 'sdn-k8s-b2-7'
```

We can check the operator work status by kubectl.
```bash
kubectl get pod -n litmus -o wide
NAME                               READY   STATUS   RESTARTS   AGE     IP          NODE
    NOMINATED NODE   READINESS GATES
chaos-operator-ce-d78fdff7-sjh4k   0/1     Error    6          6m24s   10.40.0.1   k8s-b2-
6   <none>           <none>
```

**What you expected to happen**:
normal work

**Anything else we need to know?**:
appinfo: Does this field make sense for this experiment?
