### ISSUE TITLE
Add coverage percentage for e2e test cases

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1460]
This issue is for adding the coverage percentage in the e2e pipeline which will count the test cases that have been covered in percent. This would be managed by a file say `master-plan.yml` which will contain the test plan. This test plan includes a unique Id,  name of the test, description, labels which will mark it as done or not done. On the basis of this, we will calculate the coverage percentage in one of the last stages of e2e pipeline.

**Comment by uditgaurav** [comment]
A sample entry in `master-plan.yml` is:
```
  - lid: 01
    name: "Admin mode functionality"
    description: "In this test case the application will be in some namespace and all litmus components are in one different namespace and we have to perform a successful chaos(any pod-delete, container-kill)"
    labels:
      test/feature: "Admin Mode"
      test/subFeature: "Working of Admin mode"
      test/priority: "P0"
      git/location: ""
      test/status: "Done"
```
