### ISSUE TITLE
FORCE flag in pod-delete experiments will force delete whether it´s set to false or true

### ISSUE THREAD

**Issue by xkbarkar** [litmuschaos/litmus#1507]
**What happened**:
Ran the pod-delete experiment on a deployment with 3 pods. I set the KILL_COUNT flag to 2 and the FORCE flag to false
**What you expected to happen**:
2 out of 3 pods should have died in the experiment.  
**What actually happened**:
2 out of 3 pods were terminated, since they need to reconnect to a db they took additional time to go to Running state. The pod-delete went ahead and killed the third container 
**How to reproduce it (as minimally and precisely as possible)**:
Make sure the pods take a moment to go to running state and run the experiment with a KILL_COUNT set to false
**Anything else we need to know?**:
In the source for the ansible manifest you can see that setting the FORCE flag is pointless as pods are forced either way 
```yaml
 - name: "[Inject]: Killing the application pod forcefullly"
      shell: |
        kubectl delete pod -n {{ app_ns }} --force --grace-period=0 --wait=false {{ app_pod }}
      args:
        executable: /bin/bash
      register: result
      when: "c_force is defined and c_force == 'true'"

    - name: "[Inject]: Killing the application pod"
      shell: |
        kubectl delete pod -n {{ app_ns }} --grace-period=0 --wait=false {{ app_pod }}
      args:
        executable: /bin/bash
      register: result
      when: "c_force is not defined or c_force == 'false' or c_force == ''" 
```

I suggest removing * --grace-period=0 --wait=false*  from ansible task [Inject]: Killing the application pod
