### ISSUE TITLE
Litmus attacks fail to work on OpenShift Cluster v4.3

### ISSUE THREAD

**Issue by Vijay5775** [litmuschaos/litmus#1538]
I'm trying to run Chaos tests using Litmus on OCP v4.3. I've followed all steps outlined here -> https://docs.litmuschaos.io/docs/openshift-litmus/

The output of each commands outlined in the above URL did appear as expected. But, when trying to run the experiment, it fails. I've just tried the first experiment 'container-kill' but unfortunately, can't get the container killed.

Additionally, have elevated privileges to the Service Account that I created 'container-kill-sa' and added it to 'anyuid' and 'privileged' scc's but still can't seem to able to crack.

One thing I did notice is, its triggering a 'pumba-sig-kill' container to initiate the attack (as attached and the container I'm targeting is highlighted as well). If Litmus is based on Pumba, then I doubt it will work on OCP v4.3, as Pumba developer has already confirmed that the code doesn't support CRI-O based runtime environments (which OCP v4.3 runs on and this is the case from OCP version 3.7. i.e. starting from OCP v3.7, the runtime environment is CRI-O).

Please can someone help confirm if above is the reason for attacks getting failed? If not, is there a way to get this resolved please? many thanks.

![image](https://user-images.githubusercontent.com/56160373/84068551-bd328b80-a9e6-11ea-9886-c7cd12e5615c.png)

p.s. also can't seem to figure out anything from the log (as attached)
![image](https://user-images.githubusercontent.com/56160373/84068635-e6ebb280-a9e6-11ea-99ba-4b36cba97a6c.png)

**Comment by ispeakc0de** [comment]
Yes, You are right the Pumba is not supporting the CRIO runtime. We are using the Pumba(docker) as a default one. You can use the other lib as well i.e contained.

You can override the value of `LIB` and `LIB_IMAGE` from the chaos-engine CR.
I have prepared the sample chaos-engine. It may help
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: container-kill-sa
  monitoring: false
  # It can be delete/retain
  jobCleanUpPolicy: 'delete' 
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            # specify the name of the container to be killed
            - name: TARGET_CONTAINER
              value: 'nginx'

            # provide the chaos interval
            - name: CHAOS_INTERVAL
              value: '10'

            # provide the total chaos duration
            - name: TOTAL_CHAOS_DURATION
              value: '20'
         # provide the lib here
            - name: LIB
              value: 'containerd'
        # provide the lib image here
            - name: LIB_IMAGE
              value: 'litmuschaos/container-killer:latest'

           # provide the container runtime path for containerd
           # applicable only for containerd runtime
           - name: CONTAINER_PATH
             value: '/run/containerd/containerd.sock'
```

**Comment by Vijay5775** [comment]
Thanks a lot Shubham.

For verifying the socket path, do I issue something like the below please? thanks again.
```
# cat /etc/crictl.yaml
runtime-endpoint: /var/run/crio/crio.sock
```

**Comment by ksatchit** [comment]
cc: @gprasath @ispeakc0de

**Comment by ispeakc0de** [comment]
Hi @Vijay5775 

Can you please share the following information to understand the problem?

- Logs of the containerd-helper pod i.e, `containerd-chaos-xxxxxx`, if created already and also verify the path of sock file `/var/run/crio/crio.sock` and `/etc/crictl.yaml`
- If helper pod is not created then provide the logs of the container-kill pod i.e, `container-kill-xxxx`.
- If the container-kill pod is not created then provide the logs of chaos-operator

**Comment by Vijay5775** [comment]
The pending details as below, thanks.

` /usr/libexec/crio/conmon -s -c f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf -n k8s_prometheus_prometheus-k8s-0_openshift-monitoring_b6646d09-ae9e-4182-bd05-774b10332028_1 -u f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf -r /usr/bin/runc -b /var/data/crioruntimestorage/overlay-containers/f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf/userdata --persist-dir /var/data/criorootstorage/overlay-containers/f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf/userdata -p /var/data/crioruntimestorage/overlay-containers/f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf/userdata/pidfile -P /var/data/crioruntimestorage/overlay-containers/f25882e0f18f6260555c2734f468ad9ac423ad4c775ca299c0bdabb2fe9a9fbf/userdata/conmon-pidfile -l /var/log/pods/openshift-monitoring_prometheus-k8s-0_b6646d09-ae9e-4182-bd05-774b10332028/prometheus/1.log --exit-dir /var/run/crio/exits --socket-dir-path /var/run/crio --log-level error --runtime-arg --root=/run/runc`


```
[root@kube-bqv4q0ls0pvtrrksmdug-dciglibga15-default-000003a3 crio]# pwd
/var/run/crio
[root@kube-bqv4q0ls0pvtrrksmdug-dciglibga15-default-000003a3 crio]# ls | grep sock
crio.sock
[root@kube-bqv4q0ls0pvtrrksmdug-dciglibga15-default-000003a3 crio]#
```

```
[root@kube-bqv4q0ls0pvtrrksmdug-dciglibga15-default-000003a3 crio]# more /etc/crictl.yaml
runtime-endpoint: unix:///var/run/crio/crio.sock
```


Appreciate if you can take a look and advice of a fix please? many thanks.

**Comment by ispeakc0de** [comment]
Hi @Vijay5775 

Thanks for providing all the information. I have made a few modifications to the container-kill experiment. I would be great if you will try the following experiment CR(modified according to use case)

```
apiVersion: litmuschaos.io/v1alpha1
description:
  message: "Kills a container belonging to an application pod \n"
kind: ChaosExperiment
metadata:
  name: container-kill
  version: 0.1.16
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "apps"
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "events"
          - "pods/exec"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "update"
          - "patch"
          - "delete"
    image: "litmuschaos/ansible-runner:ci"
    args:
    - -c
    - ansible-playbook ./experiments/generic/container_kill/container_kill_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:

    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    - name: TARGET_CONTAINER
      value: 'articles'

    # Period to wait before injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    # It supports pumba and containerd 
    - name: LIB
      value: 'containerd'

    # provide the chaos interval
    - name: CHAOS_INTERVAL
      value: '10'

    # provide the total chaos duration
    - name: TOTAL_CHAOS_DURATION
      value: '30'

    - name: CONTAINER_PATH
      value: '/var/run/crio/crio.sock'
    # LIB_IMAGE can be - gaiaadm/pumba:0.6.5, gprasath/crictl:ci
    # For pumba image use: gaiaadm/pumba:0.6.5
    # For containerd image use: gprasath/crictl:ci
    - name: LIB_IMAGE  
      value: 'litmuschaos/container-kill-helper:latest' 

    labels:
      name: container-kill

```
