### ISSUE TITLE
Multiple experiment/BDDs execution in parallel using github actions

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1549]
**This issue is for:**
-  Add the support for multiple experiments or BDDs execution parallelly in a random fashion using litmuschaos GitHub actions. 

Sample workflow for above:
```
 - name: Running pod-memory-hog chaos experiment
      uses: mayadata-io/github-chaos-actions@v0.1.1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        INSTALL_LITMUS: true
        APP_NS: default
        APP_LABEL: run=nginx
        APP_KIND: deployment
        EXPERIMENT_NAME: all
        EXPERIMENT_IMAGE: litmuschaos/ansible-runner
        EXPERIMENT_IMAGE_TAG: latest
        IMAGE_PULL_POLICY: Always
```
