### ISSUE TITLE
ChaosResult verdict for litmus go experiment is not getting fail when the experiment is failed

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1724]
**COMPONENT NAME**

- Litmus Go experiments (tested with Pod-Delete)

**SUMMARY**
- When the pod delete experiment is getting failed the chaosresult and chaosengine verdict is not getting `Fail` instead it is giving `Awaited`verdict. 
- The experiment was failed as wrong application details where passed and it wasn't getting the application. Other failed scenario was when the helper pod was in `Pending` state and could not come in `Running` due to lack of resources. All these conditions should give the chaosresult verdict as `Fail`. (and also in chaosengine).

**LITMUS VERSION**
```
1.5.0
```

**Comment by ispeakc0de** [comment]
@uditgaurav , Would you like to attach the logs of `chaos-pod` as well?

**Comment by uditgaurav** [comment]
**Chaos Result Verdict**
```yaml
Name:         engine-pod-delete
Namespace:    litmus
Labels:       <none>
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-07-12T01:06:00Z
  Generation:          12
  Resource Version:    7972812
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/litmus/chaosresults/engine-pod-delete
  UID:                 deb3dd8a-59a9-4417-946b-0a3c132a652f
Spec:
  Engine:      engine
  Experiment:  pod-delete
Status:
  Experimentstatus:
    Fail Step:  Verify that the AUT (Application Under Test) is running (pre-chaos)
    Phase:      Completed
    Verdict:    Awaited
Events:         <none>
```
**Chaos Engine Verdict**
```yaml
Name:         engine
Namespace:    litmus
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"litmuschaos.io/v1alpha1","kind":"ChaosEngine","metadata":{"annotations":{},"name":"engine","namespace":"litmus"},"spec":{"a...
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosEngine
Metadata:
  Creation Timestamp:  2020-07-12T01:45:54Z
  Finalizers:
    chaosengine.litmuschaos.io/finalizer
  Generation:        42
  Resource Version:  7972844
  Self Link:         /apis/litmuschaos.io/v1alpha1/namespaces/litmus/chaosengines/engine
  UID:               1ff16af1-8068-473e-aa57-40fe98f05021
Spec:
  Annotation Check:  false
  Appinfo:
    Appkind:              deployment
    Applabel:             run=nginx
    Appns:                litmus
  Chaos Service Account:  pod-delete-sa
  Components:
    Runner:
      Image:     litmuschaos/chaos-runner:latest
  Engine State:  stop
  Experiments:
    Name:  pod-delete
    Spec:
      Components:
        Env:
          Name:         TOTAL_CHAOS_DURATION
          Value:        30
          Name:         CHAOS_INTERVAL
          Value:        10
          Name:         FORCE
          Value:        
      Rank:             0
  Job Clean Up Policy:  retain
Status:
  Engine Status:  completed
  Experiments:
    Last Update Time:  2020-07-12T01:49:12Z
    Name:              pod-delete-71i5bh
    Status:            Execution Successful
    Verdict:           Awaited
Events:                <none>
```
**Experiment Logs**
```bash
udit@ubuntu ~> kubectl logs -f pod-delete-71i5bh-sstzz -n litmus
W0712 01:46:03.649373       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-07-12T01:46:03Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-07-12T01:46:03Z" level=info msg="[PreReq]: Updating the chaos result of pod-delete experiment (SOT)"
time="2020-07-12T01:46:03Z" level=info msg="The application informations are as follows" Namespace=litmus Label="run=nginx" Ramp Time=0
time="2020-07-12T01:46:03Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-07-12T01:46:03Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-07-12T01:49:04Z" level=error msg="Application status check failed due to Unable to get the pod, err: <nil>\n"
```
