### ISSUE TITLE
CPU hog experiment fails to inject chaos

### ISSUE THREAD

**Issue by iKarthik** [litmuschaos/litmus#1861]
**What happened**:
Executed pod cpu hog experiment, as listed in the example docs. pod cpu hog pod is unable to inject chaos. I see that there are errors thrown within the pod. Am trying to inject chaos into a custom built spring app published as a docker image.

**What you expected to happen**:
Expected CPU exhaustion to happen

**How to reproduce it (as minimally and precisely as possible)**:
Created a basic deployment file based on pod cpu hog described in this [link](https://docs.litmuschaos.io/docs/pod-cpu-hog/). Created a service account based exactly as specified in the same link. Chaos engine manifest also exactly looks like what was in the above mentioned link. I have replaced the app labels wherever appropriate.

Here is what i see in the pod logs 
`W0812 21:37:25.793667       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-08-12T21:37:25Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-08-12T21:37:25Z" level=info msg="[PreReq]: Updating the chaos result of pod-cpu-hog experiment (SOT)"
time="2020-08-12T21:37:25Z" level=info msg="The application informations are as follows" Namespace=mynamespace Label="app=myapp" Chaos Duration=300 Ramp Time=0
time="2020-08-12T21:37:25Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-08-12T21:37:25Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-12T21:37:25Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=myapp-569fc9f546-jff9w
time="2020-08-12T21:37:25Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-12T21:37:25Z" level=info msg="The running status of container are as follows" container=fluent-bit-sidecar Pod=myapp-569fc9f546-jff9w Status=Running
time="2020-08-12T21:37:25Z" level=info msg="The running status of container are as follows" container=lp-droopy Pod=myapp-569fc9f546-jff9w Status=Running
time="2020-08-12T21:37:25Z" level=info msg="The running status of container are as follows" container=myapp Pod=myapp-569fc9f546-jff9w Status=Running
time="2020-08-12T21:37:25Z" level=info msg="[Chaos]:Pods percentage to affect is 0"
time="2020-08-12T21:37:25Z" level=info msg="[Chaos]:Number of pods targetted: 1"
time="2020-08-12T21:37:25Z" level=info msg="The running status of container to stress is as follows" Pod=myapp-569fc9f546-jff9w Status=Running container=fluent-bit-sidecar
time="2020-08-12T21:37:25Z" level=info msg="[Chaos]:Stressing: 3 cores"
time="2020-08-12T21:37:25Z" level=info msg="[Chaos]:Waiting for: 300s"
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"md5sum\": executable file not found in $PATH": unknown
time="2020-08-12T21:37:26Z" level=info msg="[Chaos]:CPU stress error: command terminated with exit code 126"
time="2020-08-12T21:42:25Z" level=info msg="[Chaos]: Time is up for experiment: pod-cpu-hog"
/bin/sh: 1: head: not found
/bin/sh: 1: awk: not found
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
time="2020-08-12T21:42:26Z" level=info msg="[Chaos]:CPU stress error: command terminated with exit code 2"
time="2020-08-12T21:42:26Z" level=info msg="[Chaos]:CPU stress error: command terminated with exit code 2"
time="2020-08-12T21:42:26Z" level=error msg="[Error]: CPU hog failed due to command terminated with exit code 2\n"`

**Anything else we need to know?**:
Am on k8s 1.17, using docker as my container runtime. Running this experiment on K8s cluster hosted in AWS

**Comment by ksatchit** [comment]
@iKarthik , thanks for the issue. Can you please share the base image in use for the target container ?

**Comment by iKarthik** [comment]
@ksatchit We build our image from gradle:5.6.2-jdk11

**Comment by ksatchit** [comment]
@iKarthik , this is interesting. A cpu hog run against a sample deployment using `gradle:5.6.2-jdk11` does seem to inject chaos. 


- Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gradle
  name: gradle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradle
  template:
    metadata:
      labels:
        app: gradle
    spec:
      containers:
      - args:
        - -c
        - sleep 10000; exit 0
        command:
        - /bin/sh
        image: gradle:5.6.2-jdk11
        imagePullPolicy: IfNotPresent
        name: gradle
```

- ChaosExperiment: https://hub.litmuschaos.io/api/chaos/1.6.2?file=charts/generic/pod-cpu-hog/experiment.yaml

- ChaosEngine: 

```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: gradle-chaos
  namespace: default
spec:
  annotationCheck: 'false'
  engineState: 'active'
  auxiliaryAppInfo: ''
  appinfo:
    appns: 'default'
    applabel: 'app=gradle'
    appkind: 'deployment'
  chaosServiceAccount: pod-cpu-hog-sa
  monitoring: false
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-cpu-hog
      spec:
        components:
          env:
            # Provide name of target container
            # where chaos has to be injected
            - name: TARGET_CONTAINER
              value: 'gradle'

            #number of cpu cores to be consumed
            #verify the resources the app has been launched with
            - name: CPU_CORES
              value: '1'

            - name: TOTAL_CHAOS_DURATION
              value: '60' # in seconds            
```

**Comment by iKarthik** [comment]
@ksatchit thanks for the response. I used exactly what you have mentioned above, but with my image based off of gradle:5.6.2-jdk11. We  only add our artifacts into the image. Am still unable to get the injection to happen i get the below in pod logs

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"md5sum\": executable file not found in $PATH": unknown

The error seems to indicate md5sum is not on the path. But I was able to exec into my target container and do a md5sum calculation directly within the pod. Doing some searching on the error, it looks like this can happen because of the way a command is formatted. Look [here](https://stackoverflow.com/questions/27158840/docker-executable-file-not-found-in-path) for the reference. Does that mean anything to you?

**Comment by ksatchit** [comment]
Could very well be the case @iKarthik . Thank you for the info. Thinking more about this. Could you share (say, post redacting/dummifying) the way the entrypoints or commands are setup in your deployment? This could help test the changes we make for this.

**Comment by ksatchit** [comment]
@iKarthik could you please try running the experiment with this CR (same as the previous, but uses a test image with some [changes](https://github.com/litmuschaos/litmus-go/pull/81). 

```yaml
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects cpu consumption on pods belonging to an app deployment
kind: ChaosExperiment
metadata:
  name: pod-cpu-hog
  version: 0.1.14
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
    image: "ksatchit/go-runner:ci"
    imagePullPolicy: Always
    args:
    - -c
    - ./experiments/pod-cpu-hog
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '30'
    
    - name: CHAOS_INTERVAL
      value: '10'

    ## Number of CPU cores to stress
    - name: CPU_CORES
      value: '1'

    ## Percentage of total pods to target
    - name: PODS_AFFECTED_PERC
      value: ''

    ## Period to wait before and after injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    - name: LIB
      value: 'litmus'
      
    labels:
      name: pod-cpu-hog
```
