### ISSUE TITLE
err: Unable to Get the chaosengine

### ISSUE THREAD

**Issue by niebomin** [litmuschaos/litmus#2301]
err: Unable to Get the chaosengine

My environment is pretty simple. I have an azure k8s cluster, and followed this guide `https://istio.io/latest/docs/setup/getting-started/` to setup my environment. In other words, the namespace is enabled with istio injection.

Litmus is setup, and I was trying to run pod-delete experiment. Chaos runner pod is created, but I saw errors though. "pod-delete" pod is also created, but the target pod was not deleted. When I was looking at logs by `k logs -f pod-delete-4y48y4-ql64c -c pod-delete-4y48y4`, I saw error

```
Unable to initialise probes details from chaosengine, err: Unable to Get the chaosengine, err: Get \"https://10.0.0.1:443/apis/litmuschaos.io/v1alpha1/namespaces/default/chaosengines/bookinfo-chaos\": dial tcp 10.0.0.1:443: connect: connection refused
```

This is my engine yaml, https://drive.google.com/file/d/1HAaMLamHS3BZP6SDNtD_-YO1pdl46vnh/view?usp=sharing

Litmus version is 1.9.0

**Comment by ispeakc0de** [comment]
Hi @niebomin,

I am wondering about this failure. It is not able to reach kube-apiserver to get the chaosengine details. Are you facing this issue every time? You can try once again if you still face this issue then you can verify by exec inside `pod-delete-xxxx` pod and manually run the `kubectl get chaosengines bookinfo-chaos -n default` command.

**Comment by niebomin** [comment]
`kubectl get chaosengines bookinfo-chaos -n default` works good.  I guess it's because that istio is not totally ready (make sense?).  Do I need to do anything specifically for istio?

**Comment by niebomin** [comment]
And, the thing is, as long as I disable the istio auto inject, it works.

**Comment by ksatchit** [comment]
Interesting, the seems to be reproduced locally too. Has something to do w/ istio. Need to check this further

**Comment by niebomin** [comment]
Thanks.  Please...

**Comment by ksatchit** [comment]
This seems to be the cause: https://github.com/istio/istio/issues/8696

**Comment by ksatchit** [comment]
Ok we need to add the annotation `sidecar.istio.io/inject: "false"` in the chaos-runner, experiment pod & helpers to prevent sidecar injection & in turn avoid this issue in accessing kube-apiserver. Litmus supports adding custom annotations to the chaos pods via an instrumentation in the chaosengine. Please refer the example below: 

```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  annotationCheck: 'true'
  engineState: 'active'
  chaosServiceAccount: pod-delete-sa
  monitoring: false
  components:
    runner: 
      runnerannotation:
        sidecar.istio.io/inject: "false"
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components:
          experimentannotation: 
            sidecar.istio.io/inject: "false"
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            - name: CHAOS_INTERVAL
              value: '10'
            - name: FORCE
              value: 'false'
```
