### ISSUE TITLE
Support specifying hostPath type for experiments

### ISSUE THREAD

**Issue by chris-cmsoft** [litmuschaos/litmus#2410]
When running experiments which require the mounting of the underlying sockets for the container runtime, the socket path needs to be mounted as a type `Socket`.

At the moment the runner defaults to using `File`. 

With the latest Openshift update (4.6), this has broken the experiments, and they fail with message
```
MountVolume.SetUp failed for volume "cri-socket" : hostPath type check failed: /var/run/crio/crio.sock is not a socket file
```

The manifest for the pod at the mountPaths looks like 
```
volumes:
  - hostPath:
      path: /var/run/crio/crio.sock
      type: File
    name: cri-socket
```

When changing the type to `Socket`, the container mounts correctly.

In the experiment where these are mounted, a type is not currently allowed:
```
# From the operator CRD spec
hostFileVolumes:
  type: array
  items:
    type: object
    minProperties: 3
    properties:
      name:
        type: string
        minLength: 1
      mountPath:
        type: string
        minLength: 1
      nodePath:
        type: string
        minLength: 1
```

Proposed fix is to add an omittable `type` field in the `hostFileVolumes` spec, and default it in the runner to use `File`, but make it overridable from the CRD. 

There is already a property which manages the type of mount in `pkg/utils/volumeUtils.go:128`, that always defaults to `File`. This should be changed to default to File, but be overridable by a new property.
```
volumeBuilder := volume.NewBuilder().
    WithName(v.Name).
    WithHostPathAndType(
        v.NodePath,
        &hostpathTypeFile,
    )
```
