### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit

### ISSUE THREAD

**Issue by TidalPoo** [litmuschaos/litmus#2846]
## Question
I try to install litmus operator on minikube three days...
apply yuml done ok, but images can't pulled from docker hub

`Failed to pull image "litmuschaos/chaos-operator:1.13.5": rpc error: code = Unknown desc = toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

`docker login` is well (i have account on docker hub)

`docker pull` - it's pull images without any errors

anyway in docker hub
The rate limits of 100 container image requests per six hours for anonymous usage
I try install it three days, it's 12 times for 6 hours

I created `secret regcred` from instruction https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
And it doesn't work
I tried to change the yaml file and substitute
```
    spec:
      containers:
        - name: chaos-operator
          image: docker.io/litmuschaos/chaos-operator:1.13.5
      imagePullSecrets:
        - name: regcred
```

But it doesn't work, not auth

Portal images pulled ok, after i do `docker pull` but I don't think it helped

what i do wrong???

**Comment by TidalPoo** [comment]
docker hub curent limits for my account
ratelimit-limit: 200;w=21600
ratelimit-remaining: 200;w=21600

**Comment by oumkale** [comment]
Hi @TidalPoo,
Thank you, but this issue still there? This is because mainly due to limit reached, you may delete cluster and try again this issue should be resolve. 
For more about user : please refer [](https://www.docker.com/increase-rate-limits)

**Comment by TidalPoo** [comment]
I known about rate limits, in my account i have 198 pulls
ratelimit-limit: 200;w=21600
ratelimit-remaining: 198;w=21600

i'am add addon registry-creds to my minikube

```
[minikubik@chaostest ~]$ kubectl get secrets --namespace=kube-system | grep registry-creds
registry-creds-acr                               Opaque                                3      36m
registry-creds-dpr                               Opaque                                3      36m
registry-creds-ecr                               Opaque                                6      36m
registry-creds-gcr                               Opaque                                2      36m
```


add line to yaml

```
    spec:
      imagePullSecrets:
        - name: registry-creds-dpr
      serviceAccountName: litmus
      containers:
        - name: chaos-operator
          image: litmuschaos/chaos-operator:1.13.5
          command:
          - chaos-operator
          imagePullPolicy: Always
          env:
            - name: CHAOS_RUNNER_IMAGE
              value: "litmuschaos/chaos-runner:1.13.5"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-operator"

```

but steel have error

```
  Warning  Failed     2m10s (x3 over 3m28s)  kubelet            Failed to pull image "litmuschaos/chaos-operator:1.13.5": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Normal   BackOff    115s (x6 over 3m46s)   kubelet            Back-off pulling image "litmuschaos/chaos-operator:1.13.5"
  Warning  Failed     102s (x7 over 3m46s)   kubelet            Error: ImagePullBackOff
```
