### ISSUE TITLE
Self Agent fail to deploy on litmus portal deployment

### ISSUE THREAD

**Issue by Vr00mm** [litmuschaos/litmus#3066]
**What happened**:
event tracker and subscriber fail to start
![image](https://user-images.githubusercontent.com/87191932/127459611-4c79eb91-c1e3-41ce-a38e-3fa513d519be.png)

**What you expected to happen**:
I except the self agent installed 

**How to reproduce it (as minimally and precisely as possible)**:
install helm chart in any namespace not named 'litmus'

**Anything else we need to know?**:
Yes:
For event tracker, the serviceaccount is created into "oi137-litmus" namespace when clusterrolebinding looking for serviceaccount into litmus namespace.
![image](https://user-images.githubusercontent.com/87191932/127460935-f26b6422-4b56-41e7-a7b0-16114ff1942f.png)

The configmap contain the right namespace:
![image](https://user-images.githubusercontent.com/87191932/127461154-c9dd0af0-1496-4d03-831b-03be7f38d25d.png)

The database contain the right namespace:
![image](https://user-images.githubusercontent.com/87191932/127461053-9d7075c5-7f3b-4e29-902d-bc82a6156066.png)

some code link:
https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/utils/misc.go#L53
https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go#L55

**Comment by Vr00mm** [comment]
Here we set the subscriberConfiguration: https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go#L73 with the agent_namespace from os.env (from configmap)

But here we use the AgentNamespace:variable:https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/utils/misc.go#L127

This variable is set by default to litmus here: https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/utils/misc.go#L53 cause the cluster.AgentNamespace is nul or empty

Here is the fonction that collect the cluster from mongo:
https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go#L55

I added a log.Print("reqCluster: ", reqCluster)  here:
https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go#L59

The result is:
![image](https://user-images.githubusercontent.com/87191932/127493401-2b67a161-48d9-4f39-a632-c5adac0a7cf5.png)
The namespace in the table look -> 0xc00059d080 and i dont know why.

![image](https://user-images.githubusercontent.com/87191932/127493547-d289b5f0-6ffc-4708-aefc-fd3d7b5e2a6e.png)
Its good into database.

Just after the reqCluster log, we can see an error cloning, i dont know what is that.

Anyway, i dont understand why we dont use the subscriberConfiguration.AgentNamespace that got from env variable...

I dont get all understanding of the mechanisme, but i would like purpose to replace this line:
https://github.com/litmuschaos/litmus/blob/605294997286d8f7be419a67c20c5ec4efe02794/litmus-portal/graphql-server/utils/misc.go#L127

by 
```go
		newContent = strings.Replace(newContent, "#{AGENT-NAMESPACE}", subscriberConfig.AgentNamespace, -1)
```

**Comment by Vr00mm** [comment]
Whats happen with manifests when they already exist ?
![image](https://user-images.githubusercontent.com/87191932/127502945-0d23dc81-9cf8-443d-9961-290745c27e94.png)

Are they replaced ?

**Comment by Vr00mm** [comment]
I deleted clusterrole, clusterrolebindings and serviceaccounts.
I install for the first time litmus-portal with self-agent ( with the namespace from subscriberconfig )
Manifest are recreated:
![image](https://user-images.githubusercontent.com/87191932/127509395-2642132c-8c0e-46d5-92ff-45d6b2b516f2.png)

No more rbac errors !!!!
![image](https://user-images.githubusercontent.com/87191932/127509217-754509e2-41da-438b-8f0b-eeec16dff998.png)

event-tracker started successfully but I have now this error into subscriber :
![image](https://user-images.githubusercontent.com/87191932/127509611-020ff35b-61ab-4d8c-bd0b-edafced8255a.png)

So i see 3 issues here.

1 - The namespace is not correctly fetch from mongodb ( the proposal fix look working for the case )
2 - Manifest are not managed. I think there is only a check on resource name, and didnt apply new manifest if content change
2bis - Manifest are not managed !!!! If i delete my litmus portal helm release, those manifests are still there !!
3 - Subscriber error? I dont get it

**Comment by Vr00mm** [comment]
With some debug message added.

```
time="2021-07-30T11:31:13Z" level=info msg="Go Version: go1.16.6"
time="2021-07-30T11:31:13Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-07-30T11:31:13Z" level=info msg="all deployments up"
time="2021-07-30T11:31:13Z" level=info msg="all components live...starting up subscriber"
time="2021-07-30T11:31:13Z" level=info msg="<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n"
time="2021-07-30T11:31:13Z" level=fatal msg="cannot unmarshal clusterConfirmInterface"
```

**Comment by ksatchit** [comment]
Thanks for the detailed analysis @Vr00mm ! Tagging @gdsoumya & @rajdas98 to this issue

**Comment by gdsoumya** [comment]
Hi @Vr00mm, I tried to replicate the issue following the same steps on a fresh cluster and was unable to reproduce the error you are facing. I think the issue with the rbac was probably because of some old installation not being cleaned up properly. @rajdas98 can you confirm, if the resources already exists whether they are updated or not when the self-cluster is initiated?

For the subscriber connection issue you are facing can you provide more details about the setup of your portal is it using ingress or is it using node port for communication. And also would be helpful if you can share your `agent-config` configmap with us.

**Comment by Vr00mm** [comment]
Hello @ksatchit && @gdsoumya,
Thanks for you reply both of you !

I agree with the rbac issue: "the issue with the rbac was probably because of some old installation not being cleaned up properly"

For the subscriber, I did some more investigation today. I was thinking about the Traefik Ingress this week end.. And ...
We have our guilty, that Traefik Ingress 1.7 make me nightmare...

I was using this ingress for backend and the rewrite rules was not working properly: 
https://github.com/litmuschaos/litmus-helm/blob/feae7e218a9da9bf67ebfeb44effccd332d297fa/charts/litmus-2-0-0-beta/templates/ingress.yaml

https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#general-annotations
From the traefik 1.7 documentation, they don't use regex and i got something working like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/component: litmus
    app.kubernetes.io/instance: oi137-litmus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: 2.0.28-Beta9
    composant: oi137-litmus
    helm.sh/chart: litmus-2-0-0-beta-2.0.28-Beta9
    litmuschaos.io/version: 2.0.0
  name: litmus-portal
  namespace: oi137-litmus
spec:
  rules:
  - host: litmus-portal.pov.k8s.pole-emploi.intra
    http:
      paths:
      - backend:
          serviceName: litmusportal-frontend-service
          servicePort: 9091
        path: /
        pathType: ImplementationSpecific
      - backend:
          serviceName: litmusportal-server-service
          servicePort: 9002
        path: /backend
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

So, thats working now and my issue is probably a false issue due to old manifests ( thats are not managed)
