### ISSUE TITLE
wrong nodeSelector in workflow manifest

### ISSUE THREAD

**Issue by jinjiaw** [litmuschaos/litmus#3088]
**What happened**:

When creating workflow via portal, the NodeSelector provisioning could not result in a correct field in yaml manifest. 

please refer to the following snippet of workflow yaml file generated at the final step, the "nodeSelectors" should be "nodeSelector" per https://litmuschaos.github.io/litmus/experiments/chaos-resources/experiment-components/#experiment-nodeselectors. The "nodeSelectors" doesn't actually work. 

```yaml
                spec:
                  jobCleanUpPolicy: retain
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: node-drain
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: TARGET_NODE
                              value: node-1-2-3-5
                          nodeSelectors:
                            kubernetes.io/hostname: node-1-2-3-4
                        probe: []
                  annotationCheck: "false"
```
**What you expected to happen**:
The nodeSelector should be correctly added in the workflow manifest when creating workflow by following Create-workflow navigator. 

**How to reproduce it (as minimally and precisely as possible)**:
create workflow on portal and customize the experiment with NodeSelector. check the generated workflow manifest at the last step and find the "nodeSelectors" block. 

**Anything else we need to know?**:
