### ISSUE TITLE
Failure when executing Pod I/O Stress with some VOLUME_MOUNT_PATH input values

### ISSUE THREAD

**Issue by chirangaalwis** [litmuschaos/litmus#3108]
**What happened**:
Experiencing the following helper Pod failures when executing [Pod I/O Stress Experiment](https://docs.litmuschaos.io/docs/pod-io-stress/).

```
kubectl logs -f pod-io-stress-helper-cwiejs -n <namespace>
W0809 11:12:08.662327   18897 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-08-09T11:12:08Z" level=info msg="Helper Name: stress-chaos"
time="2021-08-09T11:12:08Z" level=info msg="[PreReq]: Getting the ENV variables"
time="2021-08-09T11:12:08Z" level=info msg="container ID of nginx container, containerID: ac65d9cb42b1c6a911b9b6240d5d140de66501784d35aac30f0afcd37cb528bb"
time="2021-08-09T11:12:08Z" level=info msg="[Info]: Container ID=ac65d9cb42b1c6a911b9b6240d5d140de66501784d35aac30f0afcd37cb528bb has process PID=22936"
time="2021-08-09T11:12:08Z" level=info msg="[Info]: Details of Stressor:" hdd-bytes="50%" Timeout=330 Volume Mount Path=/tmp/sample io=4 hdd=4
time="2021-08-09T11:12:08Z" level=info msg="[Info]: starting process: pause nsutil -t 22936 -p -- stress-ng --timeout 330s --io 4 --hdd 4 --hdd-bytes 50% --temp-path /tmp/sample"
time="2021-08-09T11:12:08Z" level=info msg="[Info]: Sending signal to resume the stress process"
time="2021-08-09T11:12:09Z" level=info msg="[Wait]: Waiting for chaos completion"
time="2021-08-09T11:12:09Z" level=fatal msg="helper pod failed, err: error process exited accidentally%!(EXTRA *exec.ExitError=exit status 1)"
```

The same command when executed manually inside the Pod container (NGINX in this case) works fine. Please find the attached screenshots to observe the mentioned scenario.
<img width="1019" alt="Screenshot 2021-08-09 at 16 41 30" src="https://user-images.githubusercontent.com/9444555/128708071-0a9792d8-2393-4186-b772-81a5226dc87d.png">
<img width="834" alt="Screenshot 2021-08-09 at 16 42 29" src="https://user-images.githubusercontent.com/9444555/128708082-8f9b17d8-cbe0-48d3-92e8-90a704a1b653.png">
<img width="1425" alt="Screenshot 2021-08-09 at 16 46 55" src="https://user-images.githubusercontent.com/9444555/128708085-ff277bff-067c-46aa-b772-705a9b0b416f.png">

Please see the use sample ChaosEngine.

```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: <namespace>
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: '<namespace>'
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: pod-io-stress-sa
  experiments:
    - name: pod-io-stress
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '330'

            ## specify the size as percentage of free space on the file system
            - name: FILESYSTEM_UTILIZATION_PERCENTAGE
              value: '50'

             ## provide the cluster runtime
            - name: CONTAINER_RUNTIME
              value: 'containerd'

            # provide the socket file path
            - name: SOCKET_PATH
              value: '/run/containerd/containerd.sock'

             ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: '100'

            - name: VOLUME_MOUNT_PATH
              value: '/tmp/sample'
```
