### ISSUE TITLE
Add subscriber flag to ignore SSL if using internal CA or create flag to pass in CA root to subscriber configmap

### ISSUE THREAD

**Issue by tonedefdev** [litmuschaos/litmus#3157]
**What happened**:
When enabling TLS on the ingress using an internally signed CA SSL cert the subscriber will be in a `CrashLoopBackOff` with the following error:

```sh
time="2021-08-19T16:26:32Z" level=info msg="Go Version: go1.16.7"
time="2021-08-19T16:26:32Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-08-19T16:26:32Z" level=info msg="all deployments up"
time="2021-08-19T16:26:32Z" level=info msg="all components live...starting up subscriber"
time="2021-08-19T16:26:32Z" level=fatal msg="Post \"https://my.domain.com/backend/query\": x509: certificate signed by unknown authority"
```

**What you expected to happen**:
I would expect there to be an option to pass in the CA root certificate so that the subscriber can verify against it, or be able to ignore the verification entirely

**How to reproduce it (as minimally and precisely as possible)**:
Use any internally signed CA SSL certificate to terminate TLS

**Anything else we need to know?**:
It would be nice if the subscriber service leveraged the internal service instead of requiring there be an ingress path to come back outside of the cluster into the ingress. The service is in the same namespace so I don't understand at all why it needs to leverage an http:// endpoint when it could hit the service directly using the cluster DNS service name. I tried to set it up that way but then got this errror:

```sh
time="2021-08-19T16:24:45Z" level=info msg="Go Version: go1.16.7"
time="2021-08-19T16:24:45Z" level=info msg="Go OS/Arch: linux/amd64"
time="2021-08-19T16:24:45Z" level=info msg="all deployments up"
time="2021-08-19T16:24:45Z" level=info msg="all components live...starting up subscriber"
time="2021-08-19T16:24:45Z" level=fatal msg="invalid character 'p' after top-level value"
```

**Comment by prithvi1307** [comment]
Hi, @tonedefdev can you publish the link to this issue on the slack channel as well to point it to the community?
To join the slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by aldor007** [comment]
Does anyone have a workaround for this issue?  I couldn't find info on the slack channel

**Comment by ksatchit** [comment]
This is a good one @aldor007 - we will get back on this soon! cc: @rajdas98 @gdsoumya 

>What you expected to happen:
I would expect there to be an option to pass in the CA root certificate so that the subscriber can verify against it, or be able to ignore the verification entirely

**Comment by aldor007** [comment]
Hi
Any updates?

**Comment by danibaeyens** [comment]
I still use an outdated 2.8.0 version... I'm not sure if the current architecture has been modified and this is not needed, but I can tell what I did:

1. I created a small emptyDir volume to copy the internal certs, at pod level
```
volumes:
      - emptyDir: {}
        name: certs
```
2. I mounted the volume on the subscriber container:
```
volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certs
```
3. I created a small initContainer with the volume mounted. Its image contains the internal certificates and I copied them inside the shared volume:
```
initContainers:
      - command:
        - /bin/sh
        - -c
        - cp /etc/ssl/certs/* /tmp/certs/
        image: docker.io/image-with-internal-certs:latest
        imagePullPolicy: Always
        name: certimage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/certs
          name: certs
```

And that was it. on the init phase, the internal certs are copied and the subscriber container is able to find them :)
