### ISSUE TITLE
 'pod network latency' experiment doe snot run correctly on Amazon EKS 

### ISSUE THREAD

**Issue by seanlnx** [litmuschaos/litmus#3182]
Problem:
When running the 'pod network latency' experiment on Amazon EKS cluster the chaos is never injected into the target pod.
Litmus version: 1.13.8
Kubernetes version: 1.18
EKS version: eks.6


The chaosengine terminates (after 6 mins or so), with this status:

 ```                                                                                                                                                                                                           Engine Status:  completed                                                                                                                                                                                           
Experiments:                                                                                                                                                                                                        
Experiment Pod:    pod-network-latency-fvsvm8-g722h                                                                                                                                                               
Last Update Time:  2021-08-27T21:32:42Z                                                                                                                                                                           
Name:              pod-network-latency                                                                                                                                                                            
Runner:            product-ourproduct-component-pod-network-latency-chaos-runner                                                                                                                                  
Status:            Running                                                                                                                                                                                        
Verdict:           Awaited
```

Note the 'Awaited' Verdict. In addition the event history reports the following:

```
Normal   ChaosEngineInitialized     10m    chaos-operator                                                   Identifying app under test & launching product-ourproduct-component-pod-network-latency-chaos-runner
Normal   ExperimentDependencyCheck  10m    product-ourproduct-component-pod-network-latency-chaos-runner  Experiment resources validated for Chaos Experiment: pod-network-latency                                 
Normal   ExperimentJobCreate        10m    product-ourproduct-component-pod-network-latency-chaos-runner  Experiment Job pod-network-latency-fvsvm8 for Chaos Experiment: pod-network-latency
Warning  Summary                    4m50s  pod-network-latency-fvsvm8-g722h                                 experiment: pod-network-latency, Result: Fail                                  
Normal   ExperimentJobCleanUp       4m37s  product-ourproduct-component-pod-network-latency-chaos-runner  Experiment Job: pod-network-latency-fvsvm8 will be deleted                       
Normal   ChaosEngineCompleted       4m36s  chaos-operator                                                   ChaosEngine completed, will delete or retain the resources according to jobCleanUpPolicy
```

I have been unable to identify why the 'result:Fail' is occurring. As per https://v1-docs.litmuschaos.io/docs/getstarted/ I have confirmed that the experiment has been installed:
```
➜  litmus kubectl get chaosexperiments -n ourproduct | grep pod-network-latency                                                                                                     
pod-network-latency       38d
 ```
Note other experiments work correctly, for instance 'pod dns error'. When working correctly the following events will be reported:
```
Normal  PreChaosCheck              7s       pod-dns-error-x424q6-p76lx                                    AUT: Running          
Normal  ChaosInject                5s       pod-dns-error-helper-inkxan                                   Injecting pod-dns-error chaos on application pod
```

The failing 'pod network latency' configuration is :
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: product-ourproduct-component-pod-network-latency-chaos
  namespace: ourproduct
spec:
  jobCleanUpPolicy: 'delete'
  engineState: 'active'
  appinfo:
    appns: 'ourproduct'
    applabel: 'component=component'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-latency-sa
  experiments:
    - name: pod-network-latency
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'product-ourproduct-component'

            - name: NETWORK_INTERFACE
              value: 'eth0'   

            - name: TOTAL_CHAOS_DURATION
              value: '60'

            - name: NETWORK_LATENCY
              value: '2000'  

            - name: CONTAINER_RUNTIME
              value: 'docker'

            - name: SOCKET_PATH
              value: '/var/run/docker.sock'

            - name: PODS_AFFECTED_PERC
              value: ''
```
The associated rbac: 
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-network-latency-sa
  namespace: ourproduct
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-network-latency-sa
  namespace: ourproduct
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
- apiGroups: [""]
  resources: ["pods/exec","pods/log","replicationcontrollers"]
  verbs: ["create","list","get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","list","get","delete","deletecollection"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets","daemonsets","replicasets"]
  verbs: ["list","get"]
- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  verbs: ["list","get"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["list","get"]
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-network-latency-sa
  namespace: ourproduct
  labels:
    name: pod-network-latency-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-network-latency-sa
subjects:
- kind: ServiceAccount
  name: pod-network-latency-sa
  namespace: ourproduct
```

The working 'pod dns error' configuration:
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: product-ourproduct-component-pod-dns-error-chaos
  namespace: ourproduct
spec:
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: 'ourproduct'
    applabel: 'component=component'
    appkind: 'deployment'
  chaosServiceAccount: pod-dns-error-sa
  experiments:
    - name: pod-dns-error
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: 'product-ourproduct-component'

            - name: TOTAL_CHAOS_DURATION
              value: '60'

            - name: TARGET_HOSTNAMES
              value: ''

            - name: MATCH_SCHEME
              value: 'exact'

            - name: CONTAINER_RUNTIME
              value: 'docker'

            - name: SOCKET_PATH
              value: '/var/run/docker.sock'

            - name: PODS_AFFECTED_PERC
              value: ''
```
The associated rbac:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-dns-error-sa
  namespace: ourproduct
  labels:
    name: pod-dns-error-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-dns-error-sa
  namespace: ourproduct
  labels:
    name: pod-dns-error-sa
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
- apiGroups: [""]
  resources: ["pods/exec","pods/log","replicationcontrollers"]
  verbs: ["create","list","get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","list","get","delete","deletecollection"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets","daemonsets","replicasets"]
  verbs: ["list","get"]
- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  verbs: ["list","get"]
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["list","get"]
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-dns-error-sa
  namespace: ourproduct
  labels:
    name: pod-dns-error-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-dns-error-sa
subjects:
- kind: ServiceAccount
  name: pod-dns-error-sa
  namespace: ourproduct
```
