### ISSUE TITLE
Unable to see Prometheus Metric `chaos_injection_time`

### ISSUE THREAD

**Issue by chirangaalwis** [litmuschaos/litmus#3317]
**What happened**:

During a container kill experiment (which we had on purpose setup to fail to capture failed event metrics), we are unable to see `chaos_injection_time` Prometheus metric property.

<img width="1439" alt="Screenshot 2021-10-26 at 22 57 09" src="https://user-images.githubusercontent.com/9444555/138931152-8810dcef-43fa-4d89-9b08-1d62336b3f20.png">

I have herewith attached all the Litmus experiment Pod container logs along with the used workflow definition.
[container-kill-helper-swnllj-describe.txt](https://github.com/litmuschaos/litmus/files/7420233/container-kill-helper-swnllj-describe.txt)
[container-kill-helper-swnllj.log](https://github.com/litmuschaos/litmus/files/7420234/container-kill-helper-swnllj.log)
[container-kill-ns9c2w--1-w2ds8-describe.txt](https://github.com/litmuschaos/litmus/files/7420235/container-kill-ns9c2w--1-w2ds8-describe.txt)
[container-kill-ns9c2w--1-w2ds8.log](https://github.com/litmuschaos/litmus/files/7420236/container-kill-ns9c2w--1-w2ds8.log)
[container-kill6cppq-runner-describe.txt](https://github.com/litmuschaos/litmus/files/7420237/container-kill6cppq-runner-describe.txt)
[container-kill6cppq-runner.log](https://github.com/litmuschaos/litmus/files/7420238/container-kill6cppq-runner.log)

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pod-fault-chaos-workflow-1633949684
  namespace: litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnPodSuccess
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: container-kill
            template: container-kill
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: container-kill
            path: /tmp/container-kill.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Kills a container belonging to an application pod
                kind: ChaosExperiment
                metadata:
                  name: container-kill
                  labels:
                    name: container-kill
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.1.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - apps
                          - batch
                          - apps.openshift.io
                          - argoproj.io
                          - litmuschaos.io
                        resources:
                          - jobs
                          - pods
                          - pods/log
                          - events
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - update
                          - patch
                          - delete
                          - deletecollection
                    image: litmuschaos/go-runner:2.1.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name container-kill
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: TARGET_PODS
                        value: ""
                      - name: CHAOS_INTERVAL
                        value: "10"
                      - name: SIGNAL
                        value: SIGKILL
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: TOTAL_CHAOS_DURATION
                        value: "20"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.1.0
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: container-kill
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.1.0
      container:
        args:
          - kubectl apply -f /tmp/container-kill.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:latest
    - name: container-kill
      inputs:
        artifacts:
          - name: container-kill
            path: /tmp/chaosengine-container-kill.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: container-kill
                  labels:
                    instance_id: 76cb25de-a52a-45df-80c2-6d562a485474
                    context: container-kill_litmus
                spec:
                  jobCleanUpPolicy: retain
                  engineState: active
                  appinfo:
                    appns: wso2
                    applabel: deployment=wso2is
                    appkind: statefulset
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: container-kill
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "150"
                            - name: CHAOS_INTERVAL
                              value: "150"
                            - name: CONTAINER_RUNTIME
                              value: containerd
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: TARGET_CONTAINER
                              value: "identity-server"
                            - name: SOCKET_PATH
                              value: "/run/containerd/containerd.sock"
                        probe: []
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-container-kill.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest
    - name: pod-gc-strategy
      steps:
        - - name: fail
            template: fail
          - name: succeed
            template: succeed
    - name: fail
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["exit 1"]
    - name: succeed
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["exit 0"]
```

**What you expected to happen**:
We would be able to see the `chaos_injection_time` Prometheus metric property

**How to reproduce it (as minimally and precisely as possible)**:

Provided under **What happened** section. The workflow is based on an application specific to WSO2.
