### ISSUE TITLE
Ability to import Argo Workflows and then modify as per needs

### ISSUE THREAD

**Issue by faisalchishtii** [litmuschaos/litmus#3331]
As an end user, I would like to be able to use an existing Argo Workflow yaml template, import it in Chaos Center and then modify it further. Here is a trivial example workflow that I am trying to import in Litmus Chaos and create a workflow but getting an error.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
 namespace: argo
 generateName: dag-diamond-coinflip-
 annotations:
  workflows.argoproj.io/description: |
   http looad generation defined as a DAG.
spec:
 serviceAccountName: argo
 entrypoint: diamond
 templates:
 - name: diamond
  dag:
   tasks:
   - name: A
    template: start
   - name: B
    depends: "A"
    template: generate-traffic
   - name: C
    depends: "A"
    template: generate-traffic
   - name: D
    depends: "A"
    template: generate-traffic
 - name: start
  script:
   #image: python:alpine3.6
   image: nyurik/alpine-python3-requests
   command: [python]
   source: |
    print("Start")
 - name: generate-traffic
  script:
   #image: python:alpine3.6
   image: nyurik/alpine-python3-requests
   command: [python]
   source: |
    import threading
    import requests
    def worker(num):
     """thread worker function"""
     url = 'http://1.2.3.4:32212/'
     r = requests.post(url)
     print(r.text)
    threads = []
    #for i in range(1):
    i = 1
    while True:
     t = threading.Thread(target=worker, args=(i,))
     threads.append(t)
     t.start()
     i += 1

```
![image](https://user-images.githubusercontent.com/26409919/140900059-1540f6ab-4293-44a2-802e-cefba4d1c109.png)
