### ISSUE TITLE
Chaos workflow with probe defined remain hung at the pod-delete step with error unable to initialize ChaosEngine, because of Update Error: ChaosEngine.litmuschaos.io \"pod-deleteskq4j\" is invalid: spec.experiments.spec.probe.cmdProbe/inputs.source: Invalid value

### ISSUE THREAD

**Issue by spshuklaji** [litmuschaos/litmus#3376]
Using the latest litmus 
```
kubectl apply -f https://litmuschaos.github.io/litmus/2.3.0/litmus-2.3.0.yaml
```
This is the chaos workflow created using the Litmus Portal. If a probe is added to the workflow the chaos-engine is hung at the pod-delete step.
```
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: custom-chaos-workflow-1638431593
  namespace: litmus
  creationTimestamp: null
  labels:
    cluster_id: bd420d67-6d69-4abf-a31b-38ee05259728
    subject: custom-chaos-workflow_litmus
    workflow_id: eb4ba622-e6cf-4a11-b12d-b537cfa76232
    workflows.argoproj.io/controller-instanceid: bd420d67-6d69-4abf-a31b-38ee05259728
spec:
  templates:
    - name: custom-chaos
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: pod-delete
            template: pod-delete
            arguments: {}
        - - name: revert-chaos
            template: revert-chaos
            arguments: {}
    - name: install-chaos-experiments
      arguments: {}
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/pod-delete.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Deletes a pod belonging to a deployment/statefulset/daemonset
                kind: ChaosExperiment

                metadata:
                  name: pod-delete
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.2.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - apps
                          - apps.openshift.io
                          - argoproj.io
                          - batch
                          - litmuschaos.io
                        resources:
                          - deployments
                          - jobs
                          - pods
                          - pods/log
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - events
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                          - deletecollection
                    image: litmuschaos/go-runner:2.2.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-delete
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "15"
                      - name: RAMP_TIME
                        value: ""
                      - name: FORCE
                        value: "true"
                      - name: CHAOS_INTERVAL
                        value: "5"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: TARGET_PODS
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.2.0
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/pod-delete.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        resources: {}
    - name: pod-delete
      arguments: {}
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine-pod-delete.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-delete
                  labels:
                    instance_id: 2695163e-63c7-4845-95e0-f845de986a3b
                    context: pod-delete_litmus
                    workflow_name: custom-chaos-workflow-1638431593
                spec:
                  appinfo:
                    appns: chaos-test
                    applabel: app=gateway
                    appkind: deployment
                  jobCleanUpPolicy: retain
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: ""
                        probe:
                          - name: running
                            type: httpProbe
                            mode: EOT
                            runProperties:
                              probeTimeout: 10
                              retry: 3
                              interval: 5
                              initialDelaySeconds: 5
                              stopOnFailure: false
                            httpProbe/inputs:
                              url: http://10.22.36.127:32728/q/health
                              insecureSkipVerify: false
                              responseTimeout: 300
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                  annotationCheck: "false"
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-delete.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: revert-chaos
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (2695163e-63c7-4845-95e0-f845de986a3b, )' -n
            {{workflow.parameters.adminModeNamespace}} "
        resources: {}
  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  ? startedAt
  ? finishedAt
```
In the chaos-operator log, this is the error seen. I'm not sure if it is in anyway related to https://github.com/go-logr/zapr/issues/23
```
{"level":"error","ts":1638425742.8421936,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"chaosengine-controller","request":"litmus/pod-deleteskq4j","error":"unable to initialize ChaosEngine, because of Update Error: ChaosEngine.litmuschaos.io \"pod-deleteskq4j\" is invalid: spec.experiments.spec.probe.cmdProbe/inputs.source: Invalid value: \"object\": spec.experiments.spec.probe.cmdProbe/inputs.source in body must be of type string: \"object\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```
From the workflow pod wait:
```
root@60f532b8e9e5:/src# kubectl logs custom-chaos-workflow-1638431593-487424871 -c wait -n litmus
time="2021-12-02T07:56:32.739Z" level=info msg="Starting Workflow Executor" version=v2.11.0
time="2021-12-02T07:56:32.741Z" level=info msg="Creating a K8sAPI executor"
time="2021-12-02T07:56:32.741Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: litmus/custom-chaos-workflow-1638431593-487424871) with template:\n{\"name\":\"pod-delete\",\"arguments\":{},\"inputs\":{\"artifacts\":[{\"name\":\"pod-delete\",\"path\":\"/tmp/chaosengine-pod-delete.yaml\",\"raw\":{\"data\":\"apiVersion: litmuschaos.io/v1alpha1\\nkind: ChaosEngine\\nmetadata:\\n  namespace: \\\"litmus\\\"\\n  generateName: pod-delete\\n  labels:\\n    instance_id: 2695163e-63c7-4845-95e0-f845de986a3b\\n    context: pod-delete_litmus\\n    workflow_name: custom-chaos-workflow-1638431593\\nspec:\\n  appinfo:\\n    appns: chaos-test\\n    applabel: app=gateway\\n    appkind: deployment\\n  jobCleanUpPolicy: retain\\n  engineState: active\\n  chaosServiceAccount: litmus-admin\\n  experiments:\\n    - name: pod-delete\\n      spec:\\n        components:\\n          env:\\n            - name: TOTAL_CHAOS_DURATION\\n              value: \\\"30\\\"\\n            - name: CHAOS_INTERVAL\\n              value: \\\"10\\\"\\n            - name: FORCE\\n              value: \\\"false\\\"\\n            - name: PODS_AFFECTED_PERC\\n              value: \\\"\\\"\\n        probe:\\n          - name: running\\n            type: httpProbe\\n            mode: EOT\\n            runProperties:\\n              probeTimeout: 10\\n              retry: 3\\n              interval: 5\\n              initialDelaySeconds: 5\\n              stopOnFailure: false\\n            httpProbe/inputs:\\n              url: http://10.22.36.127:32728/q/health\\n              insecureSkipVerify: false\\n              responseTimeout: 300\\n              method:\\n                get:\\n                  criteria: ==\\n                  responseCode: \\\"200\\\"\\n  annotationCheck: \\\"false\\\"\\n\"}}]},\"outputs\":{},\"metadata\":{\"labels\":{\"weight\":\"10\"}},\"container\":{\"name\":\"\",\"image\":\"litmuschaos/litmus-checker:latest\",\"args\":[\"-file=/tmp/chaosengine-pod-delete.yaml\",\"-saveName=/tmp/engine-name\"],\"resources\":{}}}"
time="2021-12-02T07:56:32.741Z" level=info msg="Waiting on main container"
time="2021-12-02T07:56:35.640Z" level=info msg="main container started with container ID: e131ccff1fdbf4a53fa54c1a5c36caabef36a0aa499a649d5202fe0bc9c28fb6"
time="2021-12-02T07:56:35.640Z" level=info msg="Starting annotations monitor"
time="2021-12-02T07:56:35.645Z" level=info msg="Waiting for container e131ccff1fdbf4a53fa54c1a5c36caabef36a0aa499a649d5202fe0bc9c28fb6 to complete"
time="2021-12-02T07:56:35.646Z" level=info msg="Starting to wait completion of containerID e131ccff1fdbf4a53fa54c1a5c36caabef36a0aa499a649d5202fe0bc9c28fb6 ..."
time="2021-12-02T07:56:35.646Z" level=info msg="Starting deadline monitor"
time="2021-12-02T08:01:32.741Z" level=info msg="Alloc=8469 TotalAlloc=41466 Sys=71360 NumGC=11 Goroutines=10"
time="2021-12-02T08:06:32.741Z" level=info msg="Alloc=6529 TotalAlloc=68672 Sys=71360 NumGC=18 Goroutines=10"
time="2021-12-02T08:11:32.741Z" level=info msg="Alloc=8234 TotalAlloc=95903 Sys=71360 NumGC=24 Goroutines=10"
time="2021-12-02T08:16:32.741Z" level=info msg="Alloc=5337 TotalAlloc=123072 Sys=71360 NumGC=31 Goroutines=10"
time="2021-12-02T08:21:32.741Z" level=info msg="Alloc=6927 TotalAlloc=150287 Sys=71360 NumGC=37 Goroutines=10"
time="2021-12-02T08:26:32.741Z" level=info msg="Alloc=8402 TotalAlloc=177485 Sys=71360 NumGC=43 Goroutines=10"
time="2021-12-02T08:31:32.741Z" level=info msg="Alloc=5739 TotalAlloc=204745 Sys=71360 NumGC=50 Goroutines=10"
```
From the workflow pod main:
```
root@60f532b8e9e5:/src# kubectl logs custom-chaos-workflow-1638431593-487424871 -c main -n litmus
W1202 07:56:34.914065       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021/12/02 07:56:34 

ChaosEngine Name : pod-deletep9lgp

2021/12/02 07:56:34 Created Resource Details: 
{pod-deletep9lgp litmuschaos.io v1alpha1 ChaosEngine litmus }
W1202 07:56:34.950463       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021/12/02 07:56:34 Starting Chaos Checker in 1min
2021/12/02 07:57:34 Checking if Engine Completed or Stopped
2021/12/02 07:58:34 Checking if Engine Completed or Stopped
2021/12/02 07:59:34 Checking if Engine Completed or Stopped
2021/12/02 08:00:35 Checking if Engine Completed or Stopped
2021/12/02 08:01:35 Checking if Engine Completed or Stopped
2021/12/02 08:02:35 Checking if Engine Completed or Stopped
2021/12/02 08:03:35 Checking if Engine Completed or Stopped
2021/12/02 08:04:35 Checking if Engine Completed or Stopped
2021/12/02 08:05:35 Checking if Engine Completed or Stopped
2021/12/02 08:06:35 Checking if Engine Completed or Stopped
2021/12/02 08:07:35 Checking if Engine Completed or Stopped
2021/12/02 08:08:35 Checking if Engine Completed or Stopped
2021/12/02 08:09:35 Checking if Engine Completed or Stopped
2021/12/02 08:10:35 Checking if Engine Completed or Stopped
2021/12/02 08:11:35 Checking if Engine Completed or Stopped
2021/12/02 08:12:35 Checking if Engine Completed or Stopped
```

How can resolve this and get the chaos-experiments running.
