### ISSUE TITLE
Litmus-Installation should use Image-Digest #openshift

### ISSUE THREAD

**Issue by bejay633** [litmuschaos/litmus#3445]
**What happened**:
-	Litmus installed on OpenShift 4.9 with offline registry 
-	We used the ImageContentSourcePolicy to provide a mirror for docker.io/litmuschaos -repositorys (example below)
-	OpenShift-Nodes still try to pull from docker.io, because the mirror is only used when the image version is provided with digest (mirror-by-digest-only: example below)
-	Pods fail with ImagePullBackOff
-	Image gets only pulled when is provided with the digest (instead of tags like „latest“ or similar) because of default registry mirror behaviour in OpenShift  

**What you expected to happen**:
Images pulled from container-registry.internal instead of docker.io

**Where can this issue be corrected? (optional)**
Helm and YAML-Files should provide image-Digest instead of version-tags. 
Example: 
docker.io/litmuschaos/litmusportal-frontend:latest = docker.io/litmuschaos/litmusportal-frontend@sha256:aaaaaa

**How to reproduce it (as minimally and precisely as possible)**:
-	Ensure docker.io is not reachable
-	Apply the attached Configs to your OpenShift Cluster
-	Try to install litmus helm charts

```
cat <<EOF | kubectl apply -f -
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: litmus
spec:
  repositoryDigestMirrors:
    - mirrors:
        - container-registry.internal/litmuschaos/litmusportal-frontend
      source: docker.io/litmuschaos/litmusportal-frontend
    - mirrors:
        - container-registry.internal/litmuschaos/litmusportal-auth-server
      source: docker.io/litmuschaos/litmusportal-auth-server
    - mirrors:
        - container-registry.internal/litmuschaos/curl
      source: docker.io/litmuschaos/curl
    - mirrors:
        - container-registry.internal/library/mongo
      source: docker.io/mongo
    - mirrors:
        - container-registry.internal/litmuschaos/litmusportal-subscriber
      source: docker.io/litmuschaos/litmusportal-subscriber
    - mirrors:
        - container-registry.internal/litmuschaos/workflow-controller
      source: docker.io/litmuschaos/workflow-controller
    - mirrors:
        - container-registry.internal/litmuschaos/litmusportal-event-tracker
      source: docker.io/litmuschaos/litmusportal-event-tracker
    - mirrors:
        - container-registry.internal/litmuschaos/mongo
      source: docker.io/litmuschaos/mongo
    - mirrors:
        - container-registry.internal/litmuschaos/chaos-exporter
      source: docker.io/litmuschaos/chaos-exporter
EOF
```

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    #image: docker.io/litmuschaos/litmusportal-frontend:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
EOF
```

**Anything else we need to know?**:
