### ISSUE TITLE
Custom CronWorkflow Schedule Not Respected

### ISSUE THREAD

**Issue by lamc** [litmuschaos/litmus#3484]
**What happened**: 
When creating custom cron workflows in chaos center by importing the YAML [as shown here](https://github.com/lamc/chaos-charts/blob/master/workflows/nasa-blue-pod-chaos/workflow_cron.yaml) the schedule isn't recognized/ respected.

**What you expected to happen**: 
If importing YAML or using pre-defined chaos workflow from my own custom chaos hub, the cron workflow schedule set in YAML is not recognized/ respected and it's required to set a schedule through UI. Next the YAML looks like this -- with two schedules:

```apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: custom-workflow-1646680408
  namespace: litmus
  labels:
    subject: custom-workflow-1646680408_litmus
spec:
  schedule: 13 14 * * 0-6
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    schedule: 00 10 * * 1-5
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 0
    workflowSpec:
      arguments:
        parameters:```

**How to reproduce it (as minimally and precisely as possible)**:
You can copy or save the YAML I linked above, or any CronWorkflow YAML and import it through chaos center & as you progress through the steps in creating workflow, the schedule set in YAML isn't respected or recognized.

**Anything else we need to know?**: N/A

**Comment by rajdas98** [comment]
cc: @amityt

**Comment by lamc** [comment]
@amityt @rajdas98 any updates on the above question?

**Comment by Jonsy13** [comment]
Hi @lamc , The [workflow](https://github.com/lamc/chaos-charts/blob/master/workflows/nasa-blue-pod-chaos/workflow_cron.yaml) that you are importing is wrong according to schema.

The workflow that you are importing is not a cron workflow. Please check the kind in line-2 `kind: Workflow`, for cron-workflow this should be `kind: CronWorkflow`

If we look at this section in manifest - 
```
  schedule: 00 10 * * 1-5
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments:
      parameters:
        - name: adminModeNamespace
          value: litmus
        - name: appNamespace
          value: djin-shared
```

The above section will be respected only if you provide `kind: CronWorkflow`, otherwise the workflow will be considered as non cron workflow.

And because ChaosCenter is considering it as non-cron workflow, that's why the final cron workflow looks like as you posted above - 
```
kind: CronWorkflow
metadata:
  name: custom-workflow-1646680408
  namespace: litmus
  labels:
    subject: custom-workflow-1646680408_litmus
spec:
  schedule: 13 14 * * 0-6
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    schedule: 00 10 * * 1-5
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 0
    workflowSpec:
      arguments:
        parameters:```
``` 

Please change the kind to `kind: CronWorkflow` and check again.
@amityt can add more information.
