### ISSUE TITLE
Add block about experiment details

### ISSUE THREAD

**Issue by blcrz** [litmuschaos/litmus#3488]
Hi folks, constantly working with litmus, we noticed the need to generate experiments with more complete informations that allows better organization and documentation in various scenarios. We added a block about the experiment details, for example "what it is expected when you run this", which can be filled in and adapted by the teams.
We believe that the changes are advantageous in several ways, especially if we consider the amount of information that can be aggregated, therefore allowing greater security and organization in the generation of experiments.
The additions are for the configuration in yaml, example inside each experiments... With the following information.
```
spec:
  description:
    affectedServices: ""
    chaosInjection: ""
    expectedBehavior: ""
    howToValidate: ""
    metrics: ""
    risk: ""
    scenario: ""
    worstCaseScenario: ""
```
Here is an example:
description:
     

> **affectedServices:** [SERVICE_NAME_ONE] , [SERVICE_NAME_TWO]
>   **chaosInjection:** Cut connections between [SERVICE_NAME_ONE] and [SERVICE_NAME_TWO].
>       **expectedBehavior:** [SERVICE_NAME]  is responsible for foo but it's expected to have a bar on the fallback.
>       **howToValidate:** make a request on the api gateway that is accessing this [SERVICE_NAME] and make sure it will respond
>       **metrics:** Low failure rate when calling this service from other internal services
>       **risk:** Mitigate
>       **scenario:** What we are trying to make sure that works
>       **worstCaseScenario:** The worst scenario would be that we drop the [SERVICE_NAME]  and it will stop the production environment.
