### ISSUE TITLE
Unable to initialize the probes

### ISSUE THREAD

**Issue by LH8PPL** [litmuschaos/litmus#3532]
**What happened**:
Deployment in Openshift, httpProbe in pod-delete expirement.
Error:
`time="2022-03-20T13:03:51Z" level=error msg="Unable to initialize the probes, err: unable to Get the chaosengine, err: v1alpha1.ChaosEngine.Spec: v1alpha1.ChaosEngineSpec.Experiments: []v1alpha1.ExperimentList: v1alpha1.ExperimentList.Spec: v1alpha1.ExperimentAttributes.Probe: []v1alpha1.ProbeAttributes: v1alpha1.ProbeAttributes.CmdProbeInputs: v1alpha1.CmdProbeInputs.Source: ReadString: expects \" or n, but found {, error found in #10 byte of ...|\"source\":{}},\"httpPr|..., bigger context ...|e\":[{\"cmdProbe/inputs\":{\"comparator\":{},\"source\":{}},\"httpProbe/inputs\":{\"insecureSkipVerify\":true,\"|..." `

**What you expected to happen**:
Probe test success.

**How to reproduce it (as minimally and precisely as possible)**:

Litmus version: 2.4.0/2.6.0/2.7.0 (tried all 3 version, no change) 

Deployment on 
Openshift 4.8.15 (Kubernetes version v1.21.1+a620f50)

File for deployment:
https://litmuschaos.github.io/litmus/2.6.0/litmus-2.6.0.yaml

Workflow:
```
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: custom-chaos-workflow-1647760231
  namespace: litmus
  creationTimestamp: null
  labels:
    cluster_id: d7087210-5aee-4220-a7be-c3914038da91
    subject: custom-chaos-workflow_litmus
    workflow_id: 287dfc50-ae1f-491f-8bed-72d10e09bd0e
    workflows.argoproj.io/controller-instanceid: d7087210-5aee-4220-a7be-c3914038da91
spec:
  templates:
    - name: custom-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: pod-delete
            template: pod-delete
            arguments: {}
        - - name: revert-chaos
            template: revert-chaos
            arguments: {}
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/pod-delete.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Deletes a pod belonging to a deployment/statefulset/daemonset
                kind: ChaosExperiment

                metadata:
                  name: pod-delete
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:latest
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-delete
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "15"
                      - name: RAMP_TIME
                        value: ""
                      - name: FORCE
                        value: "true"
                      - name: CHAOS_INTERVAL
                        value: "5"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: TARGET_PODS
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: latest
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/pod-delete.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        resources: {}
    - name: pod-delete
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine-pod-delete.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-delete
                  labels:
                    instance_id: 2a373566-d3a0-447a-98b4-171a8d9a67a3
                    context: pod-delete_litmus
                    workflow_name: custom-chaos-workflow-1647760231
                spec:
                  appinfo:
                    appns: cloudia
                    applabel: app=event-exporter
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: ""
                        probe:
                          - name: event-exporter
                            type: httpProbe
                            mode: SOT
                            runProperties:
                              probeTimeout: 15
                              retry: 5
                              interval: 5
                              initialDelaySeconds: 120
                              stopOnFailure: false
                            httpProbe/inputs:
                              url: https://test1.test.local/metrics
                              insecureSkipVerify: true
                              responseTimeout: 120
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                  annotationCheck: "false"
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-delete.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: revert-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (2a373566-d3a0-447a-98b4-171a8d9a67a3, )' -n
            {{workflow.parameters.adminModeNamespace}} "
        resources: {}
  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
```

Chaos engine:
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  generateName: pod-delete
  resourceVersion: '376947944'
  name: pod-deletez5x6b
  uid: d3223370-a53d-4e25-8b55-8c743d650bad
  creationTimestamp: '2022-03-20T11:07:59Z'
  generation: 6
  managedFields:
    - apiVersion: litmuschaos.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:context': {}
            'f:instance_id': {}
            'f:workflow_name': {}
        'f:spec':
          .: {}
          'f:annotationCheck': {}
          'f:appinfo':
            .: {}
            'f:appkind': {}
            'f:applabel': {}
            'f:appns': {}
          'f:chaosServiceAccount': {}
      manager: checker
      operation: Update
      time: '2022-03-20T11:07:59Z'
    - apiVersion: litmuschaos.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:experiments': {}
      manager: chaos-runner
      operation: Update
      time: '2022-03-20T11:08:05Z'
    - apiVersion: litmuschaos.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"chaosengine.litmuschaos.io/finalizer"': {}
        'f:spec':
          'f:components':
            .: {}
            'f:runner':
              .: {}
              'f:image': {}
              'f:resources': {}
          'f:engineState': {}
          'f:experiments': {}
        'f:status':
          .: {}
          'f:engineStatus': {}
      manager: chaos-operator
      operation: Update
      time: '2022-03-20T11:09:52Z'
  namespace: litmus
  finalizers:
    - chaosengine.litmuschaos.io/finalizer
  labels:
    context: pod-delete_litmus
    instance_id: 91ebc5f2-653e-4b9f-90ba-94f9769d41b6
    workflow_name: custom-workflow-1647774249
spec:
  annotationCheck: 'false'
  appinfo:
    appkind: deployment
    applabel: app=event-exporter
    appns: event-exporter
  chaosServiceAccount: litmus-admin
  components:
    runner:
      image: 'litmuschaos/chaos-runner:2.3.0'
      resources: {}
  engineState: stop
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            - name: CHAOS_INTERVAL
              value: '1'
            - name: FORCE
              value: 'false'
            - name: PODS_AFFECTED_PERC
          resources: {}
          statusCheckTimeouts: {}
        probe:
          - cmdProbe/inputs:
              comparator: {}
              source: {}
            httpProbe/inputs:
              insecureSkipVerify: true
              method:
                get:
                  criteria: ==
                  responseCode: '200'
                post: {}
              url: >-
                https://test1.test.local/metrics
            k8sProbe/inputs: {}
            mode: Edge
            name: check-route
            promProbe/inputs:
              comparator: {}
            runProperties:
              interval: 10
              probeTimeout: 60
              retry: 2
            type: httpProbe
status:
  engineStatus: completed
  experiments:
    - experimentPod: pod-delete-roqrf7-kgf6k
      lastUpdateTime: '2022-03-20T11:09:49Z'
      name: pod-delete
      runner: pod-deletez5x6b-runner
      status: Running
      verdict: Awaited
```
