### ISSUE TITLE
Security vulnerabilities found on gaiadocker/iproute2

### ISSUE THREAD

**Issue by rociomroman** [litmuschaos/litmus#3552]
## Details:

- We found 11 vulnerabilities marked as high on gaiadocker/iproute2. Also, appears the image has not been maintained for years, last update was 6 years ago (https://hub.docker.com/r/gaiadocker/iproute2/). And unable to even find the dockerfile for it. Would gaiaadm/pumba be a viable alternative for network chaos experiments? ref:https://github.com/litmuschaos/litmus/issues/969

```
containers:
      - image: gaiaadm/pumba:0.6.5
        imagePullPolicy: Always
        name: pumba
        # Pumba command: modify it to suite your needs
        # example: kill myserver container on minikube every 60 seconds
        # find out re2 regex string with minikube ssh; docker ps | grep myserver
        args:
          - --interval
          - "1m"
          - kill
          - --signal
          - "SIGKILL"
          - re2:k8s_myserver_myserver-6c8c7c8d9f-hqh2r
```
