### ISSUE TITLE
TLS config o SKIP_SSL_VERIFY in custom chaos hub connection?

### ISSUE THREAD

**Issue by mbecca** [litmuschaos/litmus#3789]

**Comment by avaakash** [comment]
Hi @mbecca can you describe your issue and use case for better understanding?

**Comment by mbecca** [comment]
Hi @avaakash , when i try to connect a new chaos-hub repo via https with a self-signed certificate, I have the following error on litmus-portal-server:

Error in cloningtime="2022-10-11T21:10:30Z" level=error msg="Get \"https://xxxx-gitlab.mecon.ar/grupo/repo.git/info/refs?service=git-upload-pack\": x509: certificate signed by unknown authority"

**Comment by francoischenu** [comment]
Hello, any news about this question?
I have the same problem as mbecca

**Comment by jouve** [comment]
I create a CM with the cabundle
```
kubectl create cm cabundle --from-file=ca.crt=ca.crt
```
then I mount it in graphql pod:
```yaml
portal:
  server:
    graphqlServer:
      volumes:
        - name: gitops-storage
          emptyDir: {}
        - name: hub-storage
          emptyDir: {}
        - name: certs
          configMap:
            name: cabundle
            items:
              - key: ca.crt
                path: ca-certificates.crt
      volumeMounts:
        - mountPath: /tmp/
          name: gitops-storage
        - mountPath: /tmp/version
          name: hub-storage
        - mountPath: /etc/ssl/certs/
          name: certs

```
