### ISSUE TITLE
podtato-head scenario is failing during pod-delete

### ISSUE THREAD

**Issue by awalmsley** [litmuschaos/litmus#3908]
I'm using AWS EKS, and I'm seeing the following error message in the ChaosCenter during pod-delete..
```
W0224 02:35:29.864248       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023/02/24 02:35:29 

ChaosEngine Name : podtato-main-pod-delete-chaosq4b96

2023/02/24 02:35:29 Created Resource Details: 
{podtato-main-pod-delete-chaosq4b96 litmuschaos.io v1alpha1 ChaosEngine litmus }
W0224 02:35:29.919733       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023/02/24 02:35:29 Starting Chaos Checker in 1min
2023/02/24 02:36:29 Checking if Engine Completed or Stopped
2023/02/24 02:37:29 Checking if Engine Completed or Stopped
2023/02/24 02:37:29 [*] ENGINE COMPLETED

Chaos logs unavailable
```
**Pods**
```
$ kubectl get pods -n litmus
NAME                                            READY   STATUS      RESTARTS      AGE
chaos-exporter-7f75cbb485-rmfdb                 1/1     Running     0             20h
chaos-litmus-auth-server-687676c9cf-58gc4       1/1     Running     0             20h
chaos-litmus-frontend-85956b5985-v6l2z          1/1     Running     0             20h
chaos-litmus-server-9d69b6b78-p6mb6             1/1     Running     0             20h
chaos-mongodb-5987c9f8d-vgj5k                   1/1     Running     0             20h
chaos-operator-ce-789d848bf4-dbchj              1/1     Running     0             20h
event-tracker-6cc4599dcd-dndmh                  1/1     Running     0             20h
podtato-head-1677204391-1457726460              0/2     Completed   0             14h
podtato-head-1677204391-1677206058-1275448648   0/2     Completed   0             14h
podtato-head-1677204391-1677206058-1736901251   0/2     Completed   0             14h
podtato-head-1677204391-1677206058-2091239931   0/2     Completed   0             14h
podtato-head-1677204391-1677206058-2127047913   0/2     Completed   0             14h
podtato-head-1677204391-1677206058-3327725038   0/2     Completed   0             14h
podtato-head-1677204391-3138119818              0/2     Completed   0             14h
podtato-head-1677204391-325151189               0/2     Completed   0             14h
podtato-head-1677204391-65536920                0/2     Completed   0             14h
podtato-head-1677204391-934391147               0/2     Completed   0             14h
subscriber-78d549bfbd-82bhr                     1/1     Running     1 (20h ago)   20h
workflow-controller-f646fdd7b-2j8zw             1/1     Running     0             20h
```

**Kubernetes version**
```
kubectl version  --output=yaml
clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-29T18:43:31Z"
  compiler: gc
  gitCommit: 96e7d52c98a32f2b296ca7f19dc9346cf79915ba
  gitTreeState: clean
  gitVersion: v1.23.14-eks-ffeb93d
  goVersion: go1.17.13
  major: "1"
  minor: 23+
  platform: linux/amd64

WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

**Comment by kumar-shantanu** [comment]
I am facing the same issue

**Comment by wyhysj** [comment]
yes, same issue here
latest release 2.14.0, Kubernetes version 1.25.6
```time="2023-02-28T08:17:41Z" level=error msg="The check-podtato-main-access-url http probe has been Failed, err: Get \"http://podtato-main.litmus.svc.cluster.local:9000\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

**Comment by awalmsley** [comment]
Looks like the failure was caused by the HTTP probe timeout, it was set to 1ms. It works when it is increased. e.g. 2000ms
```
                       probe:
                          - name: check-podtato-main-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://podtato-main.{{workflow.parameters.adminModeNamespace}}.svc.cluster.local:9000
                              insecureSkipVerify: false
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              **probeTimeout: 1
                              interval: 1
                              retry: 1**
 ```
