### ISSUE TITLE
GitOps triggers a Chaos Scenarios without satisfying the EventTrackerPolicy

### ISSUE THREAD

**Issue by 1180300723xiangwenqi** [litmuschaos/litmus#3930]
**What happened**:
To verify the use of GitOps, I configured the git repository and set corresponding annotations for the application under test, then I created an eventtrackerpolicy with the following content
```yaml
apiVersion: eventtracker.litmuschaos.io/v1
kind: EventTrackerPolicy
metadata:
  name: eventtrackerpolicy-sample
  namespace: litmus-ns
spec:
  condition_type: "and"
  conditions:
  - key: "spec.replicas"
    value: "3"
    operator: EqualTo
  - key: "spec.template.spec.containers[0].image"
    value: "nginx:1.21.1"
    operator: EqualTo
```
I set the value of `spec.condition_type` to `and`, theoretically, the chaos scenario will be triggered if both conditions are met, However, I encountered some unexpected situations:
* If I only update the container image version, the chaos scenario will be triggered only if both conditions are met, this phenomenon is in line with expectations
* If I update the number of replicas, regardless of whether the container image version meets the condition, as long as the number of replicas meets the condition, the chaos scenario will be triggered, this phenomenon is not in line with expectations

**What you expected to happen**:
I expect that when I set the value of `spec.condition_type` to `and`, no matter what configuration I update for my application, the chaos scenario will be triggered only if all conditions in the EventTrackerPolicy are met

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an application from the image nginx:1.18 with 1 replicas
2. Configure GitOps
3. Create a chaos scenario
4.  Set annotations for the application under test according to the litmus docs
5. Create an eventtrackerpolicy with the following content
```yaml
apiVersion: eventtracker.litmuschaos.io/v1
kind: EventTrackerPolicy
metadata:
  name: eventtrackerpolicy-sample
  namespace: litmus-ns
spec:
  condition_type: "and"
  conditions:
  - key: "spec.replicas"
    value: "3"
    operator: EqualTo
  - key: "spec.template.spec.containers[0].image"
    value: "nginx:1.21.1"
    operator: EqualTo
```
6. Update the replicas number of the application under test to 3
7. At this time, the number of replicas is 3, but the container image is nginx:1.18, which does not meet the condition, howerver, the chaos scenario will be triggered

**My Testing Environment**:
* kubernetes: 1.26.0
* CentOS: 7.9
* litmuschaos: 2.14.0
