### ISSUE TITLE
Pick Target Application by Selector instead of Label

### ISSUE THREAD

**Issue by dstoecklein** [litmuschaos/litmus#4004]
## Question
Hello, suppose i have the following two deployment definitions - note that they both have the same label. 

``my-app.yaml``:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
```

``my-app-primary.yaml``:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app-primary
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-primary
```

Now I would like to be able to select the deployment with selector ``my-app-primary``. However, the dashboard does not provide an option to specify the selector. I can only select deployment by its label, but as you can see the label are identcial in both deployments. Is this possible with Litmus?
