### ISSUE TITLE
Network latency misbehave for pods with istio-proxy

### ISSUE THREAD

**Issue by Wojciech-Chilinski** [litmuschaos/litmus#4149]
**What happened**:
I'm using a pod-network-latency experiment, scoped to a single domain.  If I'm targeting pods with my app container only, it works as expected. If I'm targeting a pod with an injected `istio-proxy` container. Latency is applied for all the egress traffic from the pod.  I was trying to set `TARGET_CONTAINER` to my app or `istio-proxy` - the same result.

**What you expected to happen**:
network latency works as documented even for istio proxy-container

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
```
               - name: pod-network-latency
                  spec:
                    components:
                      env:
                        - name: DESTINATION_HOSTS
                          value: "google.com"
                        - name: DESTINATION_IPS
                          value: '8.8.8.8'
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: NETWORK_LATENCY
                          value: "3000"
                        - name: JITTER
                          value: "30"
                        - name: TARGET_CONTAINER
                          value: istio-proxy
                        - name: CONTAINER_RUNTIME
                          value: containerd
                        - name: SOCKET_PATH
                          value: /run/containerd/containerd.sock
                        - name: PODS_AFFECTED_PERC
                          value: "100"
```
Output before chaos started:
```
~/bin $ time wget google.com
real	0m 0.07s
user	0m 0.00s
sys	0m 0.00s
~/bin $ time wget amazon.com
real	0m 0.74s
user	0m 0.00s
sys	0m 0.00s
```
Output during the chaos run:
```
~/bin $ time wget google.com
real	0m 10.13s
user	0m 0.00s
sys	0m 0.00s
~/bin $ time wget amazon.com
real	0m 23.19s
user	0m 0.00s
sys	0m 0.00s
```
**Anything else we need to know?**:
