### ISSUE TITLE
Subscriber can't install workflow in infra namespace

### ISSUE THREAD

**Issue by Wojciech-Chilinski** [litmuschaos/litmus#4183]
**What happened**:
I have a litmus agent installed in `litmus-test` ns with namespace scope. While running the experiment from UI. experiment hang in `QUEUED` state infinity. When I checked subscribers logs I saw:
```
time="2023-09-21T09:54:17Z" level=error msg="Error on processing request" error="error performing infra operationn: workflows.argoproj.io is forbidden: User \"system:serviceaccount:litmus-test:litmus\" cannot create resource \"workflows\" in API group \"argoproj.io\" in the namespace \"litmus\""
```
it clearly targeting the wrong ns. after adding additional permisions for sa, behavior is the same but error chenged to:
```
time="2023-09-21T13:20:10Z" level=error msg="Error on processing request" error="error performing infra operationn: the namespace of the provided object does not match the namespace sent on the request"
```
subscriber pod definition contains porper env:
```
  - env:
    - name: INFRA_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    envFrom:
    - configMapRef:
        name: subscriber-config
    - secretRef:
        name: subscriber-secret
    image: litmuschaos/litmusportal-subscriber:3.0.0-beta12
    imagePullPolicy: Always
    name: subscriber
```
Also workflow definition - after downloading it from webUI is defined in proper ns:
```
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: test4-gk-b8-bq
  namespace: litmus-test
...
```

**What you expected to happen**:
Subscriber is able to install workflow in proper namespace

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Please advise where else i need to setup infra-namespace.
agent version: `3.0.0-beta12`
