### ISSUE TITLE
Network latency delay having wrong delay

### ISSUE THREAD

**Issue by williamokano** [litmuschaos/litmus#4241]
**What happened**:
When I create a Chaos Experiment for Network Latency and setup with the following:

```yaml
...
                  experiments:
                    - name: pod-network-latency
                      spec:
                        components:
                          env:
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: NETWORK_INTERFACE
                              value: eth0
                            - name: LIB_IMAGE
                              value: litmuschaos/go-runner:3.0.0
                            - name: TC_IMAGE
                              value: gaiadocker/iproute2
                            - name: NETWORK_LATENCY
                              value: "2000"
                            - name: TOTAL_CHAOS_DURATION
                              value: "300"
                            - name: RAMP_TIME
                              value: ""
                            - name: JITTER
                              value: "0"
                            - name: PODS_AFFECTED_PERC
                              value: "100"
                            - name: TARGET_PODS
                              value: ""
                            - name: CONTAINER_RUNTIME
                              value: containerd
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
                            - name: DESTINATION_IPS
                              value: ""
                            - name: DESTINATION_HOSTS
                              value: jsonplaceholder.typicode.com
                            - name: SOCKET_PATH
                              value: /run/containerd/containerd.sock
                            - name: NODE_LABEL
                              value: ""
                            - name: SEQUENCE
                              value: parallel
```

The requests that were taking avg 0.005s to to run are now taking 6.005 in avg to run.

**What you expected to happen**:

As the delay is configured for 2000, I would expected the avg request time to be 2.005

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the target deployment
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-demo-okano-deployment
  namespace: test
  labels:
    app: hello-world-demo-okano
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-world-demo-okano
  template:
    metadata:
      labels:
        app: hello-world-demo-okano
    spec:
      containers:
        - name: hello-world-demo-okano
          image: docker.io/alpine/curl
          ports:
            - containerPort: 8080

          resources:
            limits:
              cpu: "750m"
              memory: "620Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          command:
            [
              'sh',
              '-c',
              'while true; do curl --silent https://jsonplaceholder.typicode.com/todos/1 -w  "%{time_starttransfer}\n"  -o /dev/null ; sleep 2; done'
            ]
```
2. Create a Chaos Experiment with a Chaos Fault of type Network Latency
3. Configure the Chaos Fault latency to 2000ms
```
        - name: NETWORK_LATENCY
          value: "2000"
```
4. Start the test

**Anything else we need to know?**:

The output of the latency test should be n + 2 seconds, but it shows n + 6 seconds, which is not intended.

At the time of the test I had 3 replicas running so I thought it would be related to the number of pods, but it's not. I tested further with 1 replica and 6 replicas and they all got 6 seconds latency instead of 2 seconds.
