### ISSUE TITLE
CONTAINER_RUNTIME_ERROR when trying to test out litmuschaos 3.0

### ISSUE THREAD

**Issue by narioinc** [litmuschaos/litmus#4245]
Environment: Minikube
minikube version: v1.31.2
commit: fd7ecd9c4599bef9f04c0986c4a0187f98a4396e
container runtime - minikube forced to use docker as container runtime via config
OS: Windows, running wsl2

Litmuschaos installation method: Helm
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
chaos   litmus          1               2023-10-27 08:11:27.2414885 +0530 IST   deployed        litmus-3.0.0    3.0.0

The chaos infra has been configured with "cluster wide access" and not namespace scoped for now. 

**What happened**:

I tried to install a fresh install of litmus 3.0 and take it for a spin as we have been extensively using the older version for our chaos tests internally. 
I was able to create the chaos infra and register the local cluster. 
I tried to create a http 500 fault for the HTTPBIN service (which was deployed using the istio sample here: https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml

Service is running on port 8000. 
Only one instance of the pod running (replica = 1)

But when running the experiment I am running into the following error:

```
{"source":"pod-http-status-code-helper-85fj8","errorCode":"CONTAINER_RUNTIME_ERROR","phase":"ChaosInject","reason":"failed to get container pid: E1027 03:20:16.491436 117340 remote_runtime.go:432] \"ContainerStatus from runtime service failed\" err=\"rpc error: code = NotFound desc = an error occurred when try to find container \\\"83bdb19e57cec8c4a7f848729e139089bf04dccc3ba027fe2cb48cfbfbcd39b4\\\": not found\" containerID=\"83bdb19e57cec8c4a7f848729e139089bf04dccc3ba027fe2cb48cfbfbcd39b4\"\ntime=\"2023-10-27T03:20:16Z\" level=fatal msg=\"getting the status of the container \\\"83bdb19e57cec8c4a7f848729e139089bf04dccc3ba027fe2cb48cfbfbcd39b4\\\": rpc error: code = NotFound desc = an error occurred when try to find container \\\"83bdb19e57cec8c4a7f848729e139089bf04dccc3ba027fe2cb48cfbfbcd39b4\\\": not found\"\n","target":"{containerID: 83bdb19e57cec8c4a7f848729e139089bf04dccc3ba027fe2cb48cfbfbcd39b4}"}
```
The container runtime has been updated in the YAML with the correct sock 

```
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: httpbin-500
  namespace: litmus
  labels:
    infra_id: 3d12edc2-ce3c-4f08-9564-26a9da980a96
    revision_id: a270a30e-8813-45ff-b18f-3f6b40627658
    workflow_id: 557f5505-356a-4634-8cd0-abaf0cb4e456
    workflows.argoproj.io/controller-instanceid: 3d12edc2-ce3c-4f08-9564-26a9da980a96
spec:
  templates:
    - name: httpbin-500
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: pod-http-status-code-fje
            template: pod-http-status-code-fje
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: pod-http-status-code-fje
            path: /tmp/pod-http-status-code-fje.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: >
                    It injects chaos inside the pod which modifies the status code of the
                    response from the provided application server to desired status code
                    provided by the user and reverts after a specified duration
                kind: ChaosExperiment

                metadata:
                  name: pod-http-status-code
                  labels:
                    name: pod-http-status-code
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 3.0.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - delete
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - delete
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:3.0.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-http-status-code
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:3.0.0
                      - name: STATUS_CODE
                        value: "500"
                      - name: MODIFY_RESPONSE_BODY
                        value: "true"
                      - name: RESPONSE_BODY
                        value: ""
                      - name: CONTENT_ENCODING
                        value: ""
                      - name: CONTENT_TYPE
                        value: text/plain
                      - name: TARGET_SERVICE_PORT
                        value: "80"
                      - name: TOXICITY
                        value: "100"
                      - name: PROXY_PORT
                        value: "20000"
                      - name: NETWORK_INTERFACE
                        value: eth0
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: DEFAULT_HEALTH_CHECK
                        value: "false"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: NODE_LABEL
                        value: ""
                      - name: SEQUENCE
                        value: serial
                    labels:
                      name: pod-http-status-code
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 3.0.0
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
            && sleep 30
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: pod-http-status-code-fje
      inputs:
        artifacts:
          - name: pod-http-status-code-fje
            path: /tmp/chaosengine-pod-http-status-code-fje.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: httpbin-500
                  annotations:
                    probeRef: '[{"name":"httpbin","mode":"Continuous"}]'
                  generateName: pod-http-status-code-fje
                spec:
                  engineState: active
                  appinfo:
                    appns: default
                    applabel: app=httpbin
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-http-status-code
                      spec:
                        components:
                          env:
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: LIB_IMAGE
                              value: litmuschaos/go-runner:3.0.0
                            - name: STATUS_CODE
                              value: "500"
                            - name: MODIFY_RESPONSE_BODY
                              value: "true"
                            - name: RESPONSE_BODY
                              value: ""
                            - name: CONTENT_ENCODING
                              value: ""
                            - name: CONTENT_TYPE
                              value: text/plain
                            - name: TARGET_SERVICE_PORT
                              value: "80"
                            - name: TOXICITY
                              value: "100"
                            - name: PROXY_PORT
                              value: "20000"
                            - name: NETWORK_INTERFACE
                              value: eth0
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: RAMP_TIME
                              value: ""
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: TARGET_PODS
                              value: ""
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
                            - name: NODE_LABEL
                              value: ""
                            - name: SEQUENCE
                              value: serial
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-pod-http-status-code-fje.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: httpbin-500
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status: {}
```

**What you expected to happen**:
The chaos experiment was supposed to inject a fault where in the service would return 500 during the duration of the fault

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:

1) Run the latest minikube
2) ensure minikube selects the "docker container runtime"
3) install httpbin from https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml in default namepace
4) create a pod http status fault and point to the httpbin service in default namespace

**Anything else we need to know?**:
