### ISSUE TITLE
litmus-portal-upgrade-agent-cp  pod in ImagePullBackoff - no such tag in dockerhub

### ISSUE THREAD

**Issue by michal-poliwka** [litmuschaos/litmus#4313]
**What happened**:
I installed litmus using  helm-chart v3.0.2. I noticed that one pod does not come up due to lack of the image in dockerhub. This is the image which is used in v3.0.2 helm-chart:
```
upgradeAgent:
  enabled: true
  controlPlane:
    image:
      repository: upgrade-agent-cp
      tag: "3.0.0"
      pullPolicy: "Always"
```

**What you expected to happen**:
Pod is Running, image  tag is present in Dockerhub
**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**:
Install litmus v3.0.2 and check whether all pods are Running|Completed
**Anything else we need to know?**:
