### ISSUE TITLE
litmus-agent Helm chart - Subscriber and Event-tracker CrashLoopBackOff: ACCESS_KEY / VERSION missing values

### ISSUE THREAD

**Issue by gustavoromerobenitez** [litmuschaos/litmus#4786]
**What happened**:

1. Deployed **litmus** Helm chart v3.9.0 on a private GKE cluster in the litmus-operator namespace via ArgoCD. 
2. The control plane components are working fine and I can access the Chaos Center UI.
3. Created an Environment.
4. Configured the **litmus-agent** Helm chart v3.9.0 as follows (credentials are redacted)
```
litmus-agent:    
  global:
    infraConfigName: test-chaos-infra-config  # This gets created but it is empty
    infraSecretName: test-chaos-infra-secret  # This gets created but it is empty
    INFRA_MODE: "cluster"
  INFRA_NAME: "test-chaos-infrastructure"
  INFRA_DESCRIPTION: "Test chaos infrastructure"
  SA_EXISTS: "false"
  NS_EXISTS: "true"
  INFRA_TYPE: "internal"
  APP_VERSION: "3.9.0"
  SKIP_SSL: "true"
  LITMUS_URL: "http://litmus-operator-app-frontend-service.litmus-operator.svc.cluster.local:9091"
  LITMUS_BACKEND_URL: "http://litmus-operator-app-server-service.litmus-operator.svc.cluster.local:9002"
  LITMUS_USERNAME: "admin"
  LITMUS_PASSWORD: "******"
  LITMUS_PROJECT_ID: "***"
  LITMUS_ENVIRONMENT_ID: "testenvironment"
```

5. Deployed litmus-agent Helm chart 3.9.0 on the same private GKE cluster in the litmus-agent namespace via Argo CD.
6. The agent installation Job finishes with an error about not being able to process the request header, but I can see the new infrastructure as PENDING in the Chaos Center UI. It never connects.
7. The subscriber workload is in a CrashLoopBackOff state and the logs show a fatal error: "required key ACCESS_KEY missing value"
8. The event-tracker workload is in a CrashLoopBackOff state and the logs show a fatal error: "required key VERSION missing value"
9. The litmus-agent namespace only contains an empty infra secret. There is no 'agent secret' as mentioned in other Issues.    

**What you expected to happen**:
I expected the infra created by the litmus-agent Helm chart to connect successfully to the Chaos Center.

**How to reproduce it (as minimally and precisely as possible)**:
See above in "What happened"

**Anything else we need to know?**:
I have searched through the issues and have followed the steps mentioned in issue [3531](https://github.com/litmuschaos/litmus/issues/3531) and issue [3528](https://github.com/litmuschaos/litmus/issues/3528) amongst others.

**Comment by thiha-singtel** [comment]
is this issue resolved?

**Comment by rakesh123822** [comment]
Im also facing this exact issue with the latest installation.

**Comment by celinegrn** [comment]
I can confirm, I am facing the same issue with flux, using latest version 3.11.0

**Comment by jemlog** [comment]
Can I take this issue?

**Comment by namkyu1999** [comment]
go ahead, @jemlog

**Comment by jemlog** [comment]
Hi, contributors.
when we deploy `litmus-agent` helm chart, this [pre-install-job](https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus-agent/templates/hook-pre-install-job.yaml) work first. 
```yaml
# hook-pre-install-job.yaml
...
spec:
      restartPolicy: Never
      serviceAccountName: {{ include "litmus-agent.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: Always
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
        args: ["./litmus-agent", "--action", "create"]
...
```
pre-install-job use container image from [this directory](https://github.com/litmuschaos/test-tools/tree/master/custom/litmus-helm-agent). 

### Analyze

Please refer to this code below from now on.

https://github.com/litmuschaos/test-tools/blob/master/custom/litmus-helm-agent/pkg/litmus/client.go#L214-L232

When execute job, we first login and get access token from auth server. For this work, we need env value `LITMUS_FRONTEND_URL`, `LITMUS_USERNAME` and `LITMUS_PASSWORD`. 

```yaml
credentials.ServerEndpoint = authInput.Endpoint # Endpoint is LITMUS_FRONTEND_URL!
```
After we logged in, credentials.ServerEndpoint is initialized by `authInput.Endpoint`. 
But it's weird, because authInput.Endpoint is frontend url, **not backend url** !

To get infrastructure info (access_key & version) from backend server, pre-install-job try to connect backend server by graphQL. Refer to the code below.

https://github.com/litmuschaos/litmusctl/blob/master/pkg/apis/infrastructure/infra.go#L104

But `apis.SendRequest()` is using credentials.ServerEndpoint and as you know, **it's frontend url**.
So.. I think it's the reason why subscriber and event-tracker are missing `ACCESS-KEY` and `VERSION`.

If my prediction is right, we need to fix [this line](https://github.com/litmuschaos/test-tools/blob/master/custom/litmus-helm-agent/pkg/litmus/client.go#L231C2-L231C49)
```go
credentials.ServerEndpoint = os.Getenv("LITMUS_BACKEND_URL")
```
