### ISSUE TITLE
Chaos manifest file subscriber fails to establish connection

### ISSUE THREAD

**Issue by bagmeg** [litmuschaos/litmus#4798]
**What happened**:
From litmus helm v3.9.0,
After installing litmus and enabling chaos, subscriber fails to establish connection. 

```
time="2024-07-30T04:34:03Z" level=info msg="Go Version: go1.22.5" 
time="2024-07-30T04:34:03Z" level=info msg="Go OS/Arch: linux/amd64" 
time="2024-07-30T04:34:03Z" level=info msg="All infra deployments are up" 
time="2024-07-30T04:34:03Z" level=info msg="Starting the subscriber" 
time="2024-07-30T04:34:03Z" level=info msg="Connecting to ws:" 
time="2024-07-30T04:34:03Z" level=fatal msg="Failed to established websocket connection" error="dial tcp :80: connect: connection refused"
```

**What you expected to happen**:
all services to work without error and connection status on web to be 'CONNECTED'

**Where can this issue be corrected? (optional)**

I've tried changing `SERVER_ADDR `on subscriber-config 
from `<ip>:<frontend nodeport>/api/query` to `http://<chaos-litmus-server-service>:9002/query` and worked.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber-config
  namespace: nginx
data:
  SERVER_ADDR: localhost:33663/api/query # http://<chaos-litmus-server-service>:9002/query
  INFRA_SCOPE: namespace
  VERSION: 3.9.1
  START_TIME: "1721551003427"
  SKIP_SSL_VERIFY: "false"
  CUSTOM_TLS_CERT: ""
  IS_INFRA_CONFIRMED: "true"
  COMPONENTS: |
    DEPLOYMENTS: ["app=chaos-exporter", "name=chaos-operator", "app=event-tracker", "app=workflow-controller"]
---
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Litmus using Helm with the following command:
`helm install chaos litmuschaos/litmus --namespace=litmus --set portal.frontend.service.type=NodePort`
2. Download (or redownload) the chaos manifest file from `/environment`
3. apply manifest file

**Anything else we need to know?**:
Test Environment
1. minikube version: v1.33.1
2. litmus helm v3.9.0, v3.8.0
