### ISSUE TITLE
Helm chart should cover installation for openshift clusters

### ISSUE THREAD

**Issue by djkormo** [litmuschaos/litmus#5113]
Helm chart should cover installation of litmus  for the openshift platform.

To move litmus to enterprise customers  using this kind of software.

Dedicated scc (security context constraint)  should be added to template rbac objects.

I think I can help with this

Proposed values excerpt

```yaml
openshift:
  enabled: true # default false for vanilla kubernetes
  anyuid: false # # if true service account will obtain permission for using anyuid scc 
```
