### ISSUE TITLE
Use Kubernetes Ansible modules instead of embedding it into the shell 

### ISSUE THREAD

**Issue by crazyglasses** [litmuschaos/litmus#808]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 FEATURE REQUEST

**What happened**:
Observed that current experiments are written with kubectl commands embedded in the shell commands. Recommend replacing it with Ansible modules for kubernetes. Eg: https://docs.ansible.com/ansible/latest/modules/k8s_module.html#synopsis
**What you expected to happen**:
If modules are embedded in the image, easier development process for new experiments as well as cleaner ansible code. 
**How to reproduce it (as minimally and precisely as possible)**:
Source Code analysis

**Anything else we need to know?**:
It is a recommendation. Would be happy to take up and convert the existing scripts to include modules and bake it into the image as well.

**Comment by ksatchit** [comment]
Awesome @crazyglasses ! That would be great ! Moving to `k8s` & `k8s_facts` is on our roadmap - will be happy to accept contributions in that area.

**Comment by ksatchit** [comment]
Tagging @uditgaurav who has been working on a similar PR!

**Comment by uditgaurav** [comment]
Thanks, @ksatchit for tagging me here@crazyglasses that's great I've been working on it and I have converted various shell commands into k8s and k8s_facts module. I have faced some issues in few commands like "Deleting the deployment" using these modules the application gets stuck into the terminating phase. I'll be happy to accept the contribution for such issues. 
**SHELL COMMAND**
```
    - name: Delete the application deployment.
      shell: kubectl delete -f {{ app_deployer }} -n {{ app_ns }}
      args:
        executable: /bin/bash
```
USING K8S MODULE
```
    - name: Delete the application deployment.
      k8s:
        state: absent
        src: "{{ app_deployer}}"
        namespace: "{{ app_ns }}" 
    
```
**OUTPUT**
```
NAME                       READY   STATUS              RESTARTS   AGE
percona-84b5758d45-6mglz   0/1     Terminating   0          2m17s
```

**Comment by uditgaurav** [comment]
Thanks, @ksatchit for tagging me here @crazyglasses that's great I've been working on it and I have converted various shell commands into k8s and k8s_facts module. I have faced some issues in few commands explained below. I'll be happy to accept the contribution for such issues. 
**SHELL COMMAND**
```
            - name: Creating busybox-liveness job
              shell: kubectl create -f {{ busybox_liveness }}
```
**USING K8S MODULE**
```
    - name: Creating busybox-liveness job
      k8s:
        state: present
        src:  {{ busybox_liveness }}
```
so what in think is  k8s module is treating it as "`kubectl apply -f` " not "`kubectl create -f `" 
it will be great if k8s module can work as "kubectl create -f" in any way.
