### ISSUE TITLE
Add the ability to delete or retain the experiments after completion.

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#857]
This is a feature requirement, that the experiments after completion should be deleted if the user specifies that the jobs should be deleted, or retain them as per the user requirements.

**New schema should look like this:**
*This would allow user to configure the engine such that deletion or retention of Jobs is taken care by the engine*
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus 
spec:
  jobCleanUpPolicy: retain 
  appinfo: 
    appns: litmus
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: "app=hello-deployment" 
  chaosServiceAccount: litmus 
  experiments:
    - name: pod-delete

```

**Comment by rahulchheda** [comment]
**New schema should look like this:**
*This would allow user to configure the engine such that deletion or retention of Jobs is taken care by the engine*
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus 
spec:
  jobCleanUpPolicy: retain 
  appinfo: 
    appns: litmus
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: "app=hello-deployment" 
  chaosServiceAccount: litmus 
  experiments:
    - name: pod-delete

```
