### ISSUE TITLE
Include custom YAML validation in the chaos-charts CI

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#878]
Ref: I think this check will retain the completed jobs even if `jobCleanUpPolicy` is something other than `retain`. Will it be ok @ksatchit @chandankumar4

_Originally posted by @Sanjay1611 in https://github.com/litmuschaos/litmus/pull/854_

The chaos experiment CRs need to be validated, both for:

- General adherence to K8s spec standards
- Custom rules regarding values accepted for specific fields

This should help mitigate experiment failures at runtime.

**Comment by rahulchheda** [comment]
*ChaosEngine Spec*
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus 
spec:
  jobCleanUpPolicy: retain 
  appinfo: 
    appns: litmus
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: "app=hello-deployment" 
  chaosServiceAccount: litmus 
  experiments:
    - name: pod-delete
      spec:
        components:
        - name: FORCE
          value: "true"
```
*jobCleanUpPolicy supported values :*
- all the strings are supported
- empty or no key value pair would also work (omit empty)
- JOB WILL ONLY DELETED WHEN jobCleanUpPolicy = "delete"
- Rather than this keyword, any would work to retain the jobs
