### ISSUE TITLE
varName inside chaoslib should be generic one

### ISSUE THREAD

**Issue by shubhamchaudhary** [litmuschaos/litmus#937]
**Requirements**

-    Put generic name inside chaoslib/utils 

**Reason**

-   There is some possible cases where `register name` and `set_fact var` may conflict because we declare the same variable inside two different but dependent files.

    -   example:
       chaoslib/lib.yml
       ```yml
        some task
        set_fact:
           app_pod: app_pod
      ```
       ansible_logic.yml
      ```yml
        some task
        register: app_pod

        including chaoslib - lib.yml
      
      want to use app_pod register
      It will create a problem because the value of app_pod variable is changed in the lib.yml.
      We can also get a error like `app_pod doesn't contain stdout`
      ```
