### ISSUE TITLE
pod-delete: refactor and make template env variables consistent

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#966]
I noticed - while trying to figure out how to use this experiment - that there are hardcoded env variables in the [pod_delete_k8s_job.yml](https://github.com/litmuschaos/litmus/blob/master/experiments/generic/pod_delete/pod_delete_k8s_job.yml) and others you have to add. I find this confusing, and it is not made very clear which values are given in the template.
I want to edit the README and the experiment itself to provide more insights to beginners. The experiment works as described in the [tutorial](https://docs.litmuschaos.io/docs/example/), but it is not very clear how env values are obtained.

**Comment by LaumiH** [comment]
It is also not clear to me why this experiment has a CHAOS_SERVICE_ACCOUNT variable and the container-kill one doesn't have one. Maybe someone could explain? The experiment works without the account variable when executed directly with hardcoded env values.

**Comment by ksatchit** [comment]
@LaumiH , here are points that may help answer.

### ENV Values in a Litmus Chaos Experiment

In the workflow explained in the docs, the env values are obtained from :

- Defaults, as defined in the [ChaosExperiment CR](https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/pod-delete/experiment.yaml). This is treated as a reference/base template to execute the experiment. Note that there is no APP envs passed here. It is more focused towards actual exp params. 

- The defaults can be *overridden* by the ChaosEngine CR, like shown below, on an instance-to-instance basis. The ChaosEngine is the *user-facing* CR, which maps an APP to *its* chaos. So we list (and reuse) an experiment template/CR while providing some overriding params (if applicable). 

```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus
spec:
  jobCleanUpPolicy: retain
  monitoring: false
  appinfo: 
    appns: default 
    applabel: "app=nginx" 
    appkind: deployment 
  chaosServiceAccount: nginx
  experiments:
    - name: pod-delete
      spec:
        components: 
          - name: TOTAL_CHAOS_DURATION
            value: '60'
          - name: CHAOS_INTERVAL
            value: '15'
```
- When the above ChaosEngine is applied, the Chaos Operator auto-constructs a final job that looks like [this job](https://github.com/litmuschaos/litmus/blob/master/experiments/generic/pod_delete/pod_delete_k8s_job.yml), just that it has all env values filled and runs it. 

- The $experiment$_k8s_job.yml is an artifact provided for users to be able to run an experiment directly after filling the values *by hand*, if they choose to do so. Some cases where this is more desirable than the operator/engine/experiment workflow is: 

  - Quick Testing
  - When users do not have the need for - batch runs, scheduled runs etc.., 
  - When an experiment has to run in a CI pipeline rather than as a service in a deployment-environment (staging/production clusters etc..,)

Mostly, the approach has been to set some default values in the above k8s_job.yaml (like duration etc.,), while leaving other info (like app ns, labels etc.,) empty. However, this choosy representation has no logical background. I would agree to the change in PR #965 where we are consistent in keeping all ENVs empty -- thereby allowing users to *hand fill* them as necessary. One addition which would be useful, however, is to add comments on the respective env key, suggesting what/how the values can be set. 

### CHAOS_SERVICE_ACCOUNT

- For non-litmus LIB (such as the chaoskube, powerfulseal or any we may add in future) it involves bringing up a new pod/deployment. These deployments too need to come up with the appropriate service account which will empower them to carry out the chaos, in this case pod-kill/delete. Since these *integrations* are launched from *within* the main experiment job, we can *choose* to pass the service account value to them as obtained from the CHAOS_SERVICE_ACCOUNT. However, it is not always necessary. I suppose powerfulseal works w/o passing this? Might be good to view the `kubectl get pod <powerfulseal pod name> -o yaml` to see what the `serviceAccount` is getting set as (`default`? v/s the one used or `chaosServiceAccount`?). 

On why the container-kill test didn't need it: There we use pumba daemonset as the agent of chaos. Pumba uses a completely different approach to "killing" -- it mounts the /var/run/docker.sock and kills the docker container on the physical node as opposed to killing a pod via a call to the Kubernetes API server (kubectl delete command). The latter is bound by the account permissions/rules etc.,

**Comment by LaumiH** [comment]
Thanks a lot, this really helped me. My question now is: where does [this](https://docs.litmuschaos.io/docs/example/) experiment get the app-specific env variables from? Or does it kill a random pod when nothing is specified and I don't notice it because I only have one pod?

**Comment by LaumiH** [comment]
I try to deploy a chaosengine looking like this:
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-1
  namespace: default
spec:
  jobCleanUpPolicy: retain
  monitoring: false
  appinfo:
    appns: default
    applabel: "run=myserver"
    appkind: deployment
  chaosServiceAccount: nginx
  experiments:
#    - name: container-kill
#      spec:
#        components:
#        - name: TARGET_CONTAINER
#          value: myserver
#        - name: APP_NAMESPACE
#          value: default
#        - name: APP_LABEL
#          value: run:myserver
    - name: pod-delete
      spec:
        components:
        - name: APP_NAMESPACE
          value: default
        - name: APP_LABEL
          value: run=myserver
        - name: APP_KIND
          value: pod
        - name: TOTAL_CHAOS_DURATION
          value: 20
        - name: CHAOS_INTERVAL
          value: 5
        - name: LIB
          value: litmus
```

The container-kill works perfectly. The pod-delete does not work at all, the chaosengine is created and nothing happens. Is this a bug or did I miss something and didn't understand the explanation @ksatchit gave me? Hm. I will continue tomorrow.

**Comment by ksatchit** [comment]
The `appinfo` part of the spec describes the pod(s) to be selected for chaos. 

```yaml
# chaosengine.yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: litmus
spec:
  jobCleanUpPolicy: retain
  monitoring: false
  appinfo: 
    # app namespace
    appns: litmus  ------> #.1 
    # to see app label, apply kubectl get pods --show-labels
    applabel: "run=myserver" ------> #.2 
    # supported kinds: deployment, statefulset
    appkind: deployment 
  chaosServiceAccount: litmus
  experiments:
    - name: pod-delete
      spec:
        components: 
``` 

Remember, earlier in this example, you did `kubectl run myserver --image=nginx -n litmus`. This creates the pod with -->#.2 

```
root@demo:~# kubectl get pods -n litmus --show-labels
NAME                       READY   STATUS    RESTARTS   AGE   LABELS
myserver-5f7d44584-tdhsb   1/1     Running   0          13s   pod-template-hash=5f7d44584,run=myserver
```
