### ISSUE TITLE
pumba: update docker image to version 0.6.5

### ISSUE THREAD

**Issue by LaumiH** [litmuschaos/litmus#969]
The idea is to update the pumba docker image used in different experiements, because new functionality comes with newer pumba versions, like netem corrupt and duplicate command added, run netem in parallel on multiple containers.

The drawback: the execution logic changed with pumba version 0.6, as described [here](https://github.com/alexei-led/pumba#running-inside-docker-container). The problem is that e.g. the `kubectl exec ... -- pumba kill` command would not work any more because the pumba docker container is now only a scratch image only containing the pumba binary.

New pumba is executed passing several args while creating the daemonset, like 
```
containers:
      - image: gaiaadm/pumba:0.6.5
        imagePullPolicy: Always
        name: pumba
        # Pumba command: modify it to suite your needs
        # example: kill myserver container on minikube every 60 seconds
        # find out re2 regex string with minikube ssh; docker ps | grep myserver
        args:
          - --interval
          - "1m"
          - kill
          - --signal
          - "SIGKILL"
          - re2:k8s_myserver_myserver-6c8c7c8d9f-hqh2r
```

The args would have to be generated/ retrieved from the sepcific experiment before deploying the daemonset. As of today, pumba is first started in dry-run mode and then given the exact command to execute via `kubectl exec`.
