### ISSUE TITLE
Enhance the EBS disk attach playbooks to factor in existing device names on VM instance

### ISSUE THREAD

**Issue by chandankumar4** [litmuschaos/litmus#99]
##  FEATURE REQUEST?
- Attach multiple EBS Volume to AWS instances by looking for available disk name inside instances.
- Recommended disk name for EBS volume is - `/dev/sd[f-p]` 

**for example: -** 
 - At the time of attaching EBS Volume in instances if `dev/sdf` disk name already present then use the next available like`dev/sdg` 

Currently used ansible module for creating EBS Volume
```
        - name: Creating and attaching EBS Volume in AWS
          ec2_vol:
            instance: i-0820e863967d14dc0
            device_name: /dev/xvdb
            region: eu-west-2
            state: present
            volume_size: 50
            volume_type: gp2
            zone: eu-west-2a
```
Disk name is auto generated by ansible module if `device_name` is not specified but currently it not check for available disk name.

Reference :- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
